### ISSUE TITLE
Invalid value tcp://10.0.35.234:9092 for configuration port: Not a number of type INT

### ISSUE THREAD

**Issue by aliakhtar** [wurstmeister/kafka-docker#122]
I'm following http://www.defuze.org/archives/351-running-a-zookeeper-and-kafka-cluster-with-kubernetes-on-aws.html in order to deploy Kafka on Kubernetes.

This is what my configuration looks like:

```
containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zk1:2181,zk2:2181,zk3:2181
            - name: KAFKA_CREATE_TOPICS
              value: test:1:1
```

The hostname `kafka` is resolved internally to the IP of the kafka service, which in this case is `10.0.35.234`.

When I run this, the container crashes. These are the logs I see:

```
awk: cmd. line:1: Unexpected token
creating topics: test:1:1
[2016-09-15 17:00:09,293] FATAL  (kafka.Kafka$)
org.apache.kafka.common.config.ConfigException: Invalid value tcp://10.0.35.234:9092 for configuration port: Not a number of type INT
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:670)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:418)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:55)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:759)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:743)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:740)
	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
	at kafka.Kafka$.main(Kafka.scala:58)
	at kafka.Kafka.main(Kafka.scala)
```

After this, it fails while creating the topic because replication factor = 1 and brokers = 0.

Why is it using `tcp://10.0.35.234:9092` as the value of the port?

**Comment by emosbaugh** [comment]
after some digging around i believe this has to do with kubernetes writing an env var KAFKA_. i would try renaming things other than kafka.

**Comment by it-svit** [comment]
Seems that if you have service called kafka, kubernetes creates environment variable called KAFKA_PORT="tcp://x.x.x.x:9092"

**Comment by it-svit** [comment]
Yes, when I changed a name of service from 'kafka' to 'kafka-cluster' it stopped crashing.

**Comment by alexyarochkin** [comment]
I added in my compose file (i'm using kompose up to deploy my cluster). And it looks like solved the issue.
environment:
   KAFKA_PORT: 9092

**Comment by spicysomtam** [comment]
I hit this issue too. In Openshift that uses kubernetes. My openshift service was renamed to kafkaa and it solved the problem.

**Comment by abitrolly** [comment]
Same here. Had to rename kubernetes service from `kafka` to something else.

**Comment by timm088** [comment]
You can use `unset KAFKA_PORT` as per the detail listed here https://github.com/confluentinc/cp-docker-images/issues/388 then you wont have the issue (and wont need to rename the service)

Unfortunately, until start scripts stop failure on the setting on `KAFKA_PORT` and/or kafka startup stops recognising this as an ENVVAR it should use at startup, workaround will have to remain in place

**Comment by abhishekkarigar** [comment]
add this to environment in docker-compose .yml **KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE**

**Comment by meetchandan** [comment]
can anyone please share the docker-compose for kafka?
Even after renaming to `kafka-cluster` or `kafkaa` and then running on kubernetes, I am getting the same error shared above.

`org.apache.kafka.common.config.ConfigException: Invalid value tcp://10.106.136.1:9092 for configuration port: Not a number of type INT`

**Comment by meetchandan** [comment]
never mind, I solved it by adding KAFKA_PORT env variable

**Comment by lauvinson** [comment]
> 是的，当我将服务名称从“ kafka”更改为“ kafka-cluster”时，它不再崩溃。

great

**Comment by kapekost** [comment]
for eks.yaml files that env var can't be INT,  but worked by setting the 
- name: KAFKA_ADVERTISED_PORT
  value: "9092

**Comment by RPalejiya** [comment]
> 
> 
> Seems that if you have service called kafka, kubernetes creates environment variable called KAFKA_PORT="tcp://x.x.x.x:9092"

This is fix for me too.
