### ISSUE TITLE
Error: java.net.UnknownHostException: opt

### ISSUE THREAD

**Issue by who** [wurstmeister/kafka-docker#126]
Command:

```
docker exec -it kafkadocker_kafka_1 bash -c './$KAFKA_HOME/bin/kafka-consumer-groups.sh --zookeeper $KAFKA_ZOOKEEPER_CONNECT --list'
```

Output:
```
log4j:ERROR Could not read configuration file from URL [file://opt/kafka_2.11-0.10.0.1/bin/../config/tools-log4j.properties].
java.net.UnknownHostException: opt
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:957)
	at sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:917)
	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1012)
	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:998)
	at sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:294)
	at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:393)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:557)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.slf4j.impl.Log4jLoggerFactory.<init>(Log4jLoggerFactory.java:66)
	at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:72)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:45)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at org.apache.kafka.common.security.JaasUtils.<clinit>(JaasUtils.java:30)
	at kafka.admin.ConsumerGroupCommand$ZkConsumerGroupService.<init>(ConsumerGroupCommand.scala:135)
	at kafka.admin.ConsumerGroupCommand$.main(ConsumerGroupCommand.scala:58)
	at kafka.admin.ConsumerGroupCommand.main(ConsumerGroupCommand.scala)
log4j:ERROR Ignoring configuration file [file://opt/kafka_2.11-0.10.0.1/bin/../config/tools-log4j.properties].
log4j:WARN No appenders could be found for logger (org.I0Itec.zkclient.ZkConnection).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN No appenders could be found for logger (org.I0Itec.zkclient.ZkEventThread).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

Here's my image details:

```
$ docker images wurstmeister/kafka 
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
wurstmeister/kafka   latest              c943e4d8bb00        3 weeks ago         261 MB
```

**Comment by wurstmeister** [comment]
```docker exec -it 464bdb3414aa bash -c '$KAFKA_HOME/bin/kafka-consumer-groups.sh --zookeeper $KAFKA_ZOOKEEPER_CONNECT --list'```
