### ISSUE TITLE
[question] kafka cannot consume any messages just after established

### ISSUE THREAD

**Issue by ynqa** [wurstmeister/kafka-docker#127]
As of title, I hope to confirm when kafka completely stands up. It accepts the messages without errors, however, none of them are consumed.
I guess that until the following logs are finished flowing, kafka cannot consume them. In other words kafka works well after outputted, so I would rather confirm it than resolve the cause.

kafka's version is `kafka-0.9.0.0` with `scala-2.11`

Logs:

```
[2016-09-20 15:21:13,286] WARN Error while fetching metadata with correlation id 7318 : {<topic_name>=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2016-09-20 15:21:15,090] WARN Error while fetching metadata with correlation id 7319 : {<topic_name>=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2016-09-20 15:21:15,202] WARN Error while fetching metadata with correlation id 7320 : {<topic_name>=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
.
.
.
[2016-09-20 15:21:33,152] WARN Error while fetching metadata with correlation id 7525 : {<topic_name>=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2016-09-20 15:21:33,259] WARN Error while fetching metadata with correlation id 7527 : {<topic_name>=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2016-09-20 15:21:34,205] ERROR Error ILLEGAL_GENERATION occurred while committing offsets for group console-consumer-30842 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2016-09-20 15:21:34,205] WARN Auto offset commit failed:  (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
```

Also you execute the following script **on local** before running kafka image, and can see these logs.

```
kafka_2.11-0.9.0.0/bin/kafka-console-consumer.sh \
--topic <topic_name> \
--new-consumer -bootstrap-server <docker_host> (if you use docker machine, you can confirm host ip with `docker_machine ip <machine_name>`)
```

**Comment by ynqa** [comment]
I also check #85, but there is no logs like the last 2 lines:

```
[2016-09-20 15:21:34,205] ERROR Error ILLEGAL_GENERATION occurred while committing offsets for group console-consumer-30842 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2016-09-20 15:21:34,205] WARN Auto offset commit failed:  (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
```

In addition, this logs always stops 1 or 2 minutes passed, not persistent.

**Comment by xiaomayilj** [comment]
i`m faced with similar problem with you when i use the project,and the error from kafka is:
`kafka_1      | [2016-09-26 07:42:21,655] ERROR [KafkaApi-1002] Error when handling request {topics=[__consumer_offsets]} (kafka.server.KafkaApis)
kafka_1      | kafka.admin.AdminOperationException: replication factor: 3 larger than available brokers: 1
kafka_1      | 	at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:117)
kafka_1      | 	at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:403)
kafka_1      | 	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createTopic(KafkaApis.scala:629)
kafka_1      | 	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createGroupMetadataTopic(KafkaApis.scala:651)
kafka_1      | 	at kafka.server.KafkaApis$$anonfun$29.apply(KafkaApis.scala:668)
kafka_1      | 	at kafka.server.KafkaApis$$anonfun$29.apply(KafkaApis.scala:666)
kafka_1      | 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
kafka_1      | 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
kafka_1      | 	at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
kafka_1      | 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
kafka_1      | 	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
kafka_1      | 	at scala.collection.SetLike$class.map(SetLike.scala:92)
kafka_1      | 	at scala.collection.AbstractSet.map(Set.scala:47)
kafka_1      | 	at kafka.server.KafkaApis.getTopicMetadata(KafkaApis.scala:666)
kafka_1      | 	at kafka.server.KafkaApis.handleTopicMetadataRequest(KafkaApis.scala:727)
kafka_1      | 	at kafka.server.KafkaApis.handle(KafkaApis.scala:79)
kafka_1      | 	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
kafka_1      | 	at java.lang.Thread.run(Thread.java:745)
`

**Comment by sscaling** [comment]
Please check the wiki page: https://github.com/wurstmeister/kafka-docker/wiki/Connectivity

It sounds like a configuration issue. Closing due to staleness.
