### ISSUE TITLE
'A broker is already registered' issue

### ISSUE THREAD

**Issue by imochurad** [wurstmeister/kafka-docker#165]
This problem happens every other time on the start up. 
In order to resolve this I have to run: 

docker-compose kill

And then start it again.

Container version:
wurstmeister/kafka       0.10.0.1            81e882f835b2        5 months ago        261 MB

kafka_1      | [2017-01-27 21:47:15,462] FATAL [Kafka Server 1001], Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka_1      | java.lang.RuntimeException: A broker is already registered on the path /brokers/ids/1001. This probably indicates that you either have configured a brokerid that is already in use, or else you have shutdown this broker and restarted it faster than the zookeeper timeout so it appears to be re-registering.
kafka_1      |     at kafka.utils.ZkUtils.registerBrokerInZk(ZkUtils.scala:305)
kafka_1      |     at kafka.utils.ZkUtils.registerBrokerInZk(ZkUtils.scala:291)
kafka_1      |     at kafka.server.KafkaHealthcheck.register(KafkaHealthcheck.scala:70)

**Comment by lbrito1** [comment]
I've been getting this as well.

From the error message: 
>... or else you have shutdown this broker and restarted it faster than the zookeeper timeout so it appears to be re-registering.

So we just have to stop the zookeeper container _after_ stopping the kafka container. I'm using this script and so far haven't had the error again:

```
#!/bin/bash

docker-compose stop kafka
docker-compose stop zookeeper <my_other_containers>
```

**Comment by maxjacobson** [comment]
Fwiw I was seeing this on [0.9.0.1](https://github.com/wurstmeister/kafka-docker/releases/tag/0.9.0.1) but not on [0.9.0.1-1](https://github.com/wurstmeister/kafka-docker/releases/tag/0.9.0.0-1). I think the backported fix resolved it for me.

**Comment by sscaling** [comment]
@imochurad - is this still an issue with the current image? There Kafka process should shutdown gracefully.
