### ISSUE TITLE
Zero brokers after running start-kafka-shell.sh

### ISSUE THREAD

**Issue by menorah84** [wurstmeister/kafka-docker#197]
I am running Kafka Docker in my Docker Quickstart Terminal (Windows 7, Docker Toolbox, VirtualBox). As of this time, I have the latest version.

In the tutorial, I get to the part where I need to start Kafka Shell.

`$  start-kafka-shell.sh  192.168.99.101  kafkadocker_zookeeper_1:2181`

which brings me to bash. However, when I attempt to create a topic:

```
$ $KAFKA_HOME/bin/kafka-topics.sh --create --topic topic \
--partitions 4 --zookeeper $ZK --replication-factor 2
```

I am getting this message:

```
Exception in thread "main" org.I0Itec.zkclient.exception.ZkException: Unable to
connect to kafkadocker_zookeeper_1:2181
        at org.I0Itec.zkclient.ZkConnection.connect(ZkConnection.java:72)
        at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1228)
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:157)
        at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:131)
        at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:106)
        at kafka.utils.ZkUtils$.apply(ZkUtils.scala:88)
        at kafka.admin.TopicCommand$.main(TopicCommand.scala:56)
        at kafka.admin.TopicCommand.main(TopicCommand.scala)
Caused by: java.net.UnknownHostException: kafkadocker_zookeeper_1: System error
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:132
3)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvi
der.java:61)
        at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445)
        at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:380)
        at org.I0Itec.zkclient.ZkConnection.connect(ZkConnection.java:70)
```
When I try to open the shell by replacing the ZooKeeper with an IP and creating a topic again:
`$  start-kafka-shell.sh  192.168.99.101  192.168.99.101:2181`

```
$ $KAFKA_HOME/bin/kafka-topics.sh --create --topic topic \
--partitions 4 --zookeeper $ZK --replication-factor 2
```
This is the message I get
```
Error while executing topic command : replication factor: 2 larger than availabl
e brokers: 0
[2017-06-16 21:50:52,959] ERROR org.apache.kafka.common.errors.InvalidReplicatio
nFactorException: replication factor: 1 larger than available brokers: 0
 (kafka.admin.TopicCommand$)
```
So, there is no Kafka broker running. Anything wrong with my docker-compose steps?

**Comment by krisleech** [comment]
Isn't it:

`$ start-kafka-shell.sh 192.168.99.100 192.168.99.101:2181`

Kafka is on UP ending 100 and ZK is on IP ending 101?

**Comment by litongyu** [comment]
As @krisleech says, use ip as the ZooKeeperName. @menorah84

**Comment by sscaling** [comment]
@menorah84  - I've recently published https://github.com/wurstmeister/kafka-docker/wiki/Connectivity wiki page. I can't help with the Windows specific issue, but it may give you some guidance on the requirements for connectivity.
