### ISSUE TITLE
Problem connecting to kafka from outside

### ISSUE THREAD

**Issue by nfazekas** [wurstmeister/kafka-docker#207]
Hi,

I have deployed this docker image in swarm mode and if I enter the container and use the console producer/console consumer everything works fine. 

My problem appears when I want to connect to kafka from an external java client. The client blocks and in the kafka-docker logs I found:

```
org.apache.kafka.common.KafkaException: Error creating mbean attribute for metricName :MetricName [name=request-time, group=Request, description=Tracking request-time per user/client-id, tags={client-id=localhost:9092, user=}]
        at org.apache.kafka.common.metrics.JmxReporter.addAttribute(JmxReporter.java:117)
        at org.apache.kafka.common.metrics.JmxReporter.metricChange(JmxReporter.java:80)
        at org.apache.kafka.common.metrics.Metrics.registerMetric(Metrics.java:504)
        at org.apache.kafka.common.metrics.Sensor.add(Sensor.java:255)
        at org.apache.kafka.common.metrics.Sensor.add(Sensor.java:240)
        at kafka.server.SensorAccess.getOrCreate(SensorAccess.scala:68)
        at kafka.server.ClientQuotaManager.getOrCreateQuotaSensors(ClientQuotaManager.scala:382)
        at kafka.server.KafkaApis.sendResponseMaybeThrottle(KafkaApis.scala:2006)
        at kafka.server.KafkaApis.sendResponseMaybeThrottle(KafkaApis.scala:1995)
        at kafka.server.KafkaApis.sendResponseCallback$8(KafkaApis.scala:1307)
        at kafka.server.KafkaApis.sendResponseWithDuplicatesCallback$1(KafkaApis.scala:1339)
        at kafka.server.KafkaApis.$anonfun$handleCreateTopicsRequest$8(KafkaApis.scala:1346)
        at kafka.server.KafkaApis.$anonfun$handleCreateTopicsRequest$8$adapted(KafkaApis.scala:1346)
        at kafka.server.DelayedCreateTopics.onComplete(DelayedCreateTopics.scala:77)
        at kafka.server.DelayedOperation.forceComplete(DelayedOperation.scala:66)
        at kafka.server.DelayedCreateTopics.tryComplete(DelayedCreateTopics.scala:58)
        at kafka.server.DelayedOperation.safeTryComplete(DelayedOperation.scala:104)
        at kafka.server.DelayedOperationPurgatory$Watchers.tryCompleteWatched(DelayedOperation.scala:338)
        at kafka.server.DelayedOperationPurgatory.checkAndComplete(DelayedOperation.scala:244)
        at kafka.server.AdminManager.tryCompleteDelayedTopicOperations(AdminManager.scala:60)
        at kafka.server.KafkaApis.$anonfun$handleUpdateMetadataRequest$2(KafkaApis.scala:225)
        at kafka.server.KafkaApis.$anonfun$handleUpdateMetadataRequest$2$adapted(KafkaApis.scala:224)
        at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
        at kafka.server.KafkaApis.handleUpdateMetadataRequest(KafkaApis.scala:224)
        at kafka.server.KafkaApis.handle(KafkaApis.scala:103)
        at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:66)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.management.MalformedObjectNameException: Invalid character ':' in value part of property
        at javax.management.ObjectName.construct(ObjectName.java:618)
        at javax.management.ObjectName.<init>(ObjectName.java:1382)
        at org.apache.kafka.common.metrics.JmxReporter$KafkaMbean.<init>(JmxReporter.java:173)
        at org.apache.kafka.common.metrics.JmxReporter.addAttribute(JmxReporter.java:112)
        ... 26 more
```

How can I fix this?

Thank you

**Comment by deventh** [comment]
https://github.com/apache/kafka/pull/4173 ?

**Comment by sscaling** [comment]
@nfazekas - is this still an issue?

If so can you provide details of docker version, os version, any additional logs. Also I think if this is a swarm-specific issue then including your stack yml file. Thanks.

**Comment by sscaling** [comment]
Closing due to staleness. Please reopen if issue persists.
