### ISSUE TITLE
Unable to create compacted topics

### ISSUE THREAD

**Issue by robbmj-index-exchange** [wurstmeister/kafka-docker#248]
Compose File:
```
kafka:
       image: wurstmeister/kafka
# ...
       environment:
            KAFKA_CREATE_TOPICS: "test-topic:2:1,fact-artifact-request:2:1:compact,fact-artifact-update:2:1:compact,commit-log:2:1:compact"
# ...
```

```
creating topics: test-topic:2:1
creating topics: fact-artifact-request:2:1:compact
creating topics: fact-artifact-update:2:1:compact
creating topics: commit-log:2:1:compact
Exception in thread "main" joptsimple.UnrecognizedOptionException: config cleanup.policy is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
	at joptsimple.OptionParser.parse(OptionParser.java:396)
	at kafka.admin.TopicCommand$TopicCommandOptions.<init>(TopicCommand.scala:352)
	at kafka.admin.TopicCommand$.main(TopicCommand.scala:44)
	at kafka.admin.TopicCommand.main(TopicCommand.scala)
Exception in thread "main" joptsimple.UnrecognizedOptionException: config cleanup.policy is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
	at joptsimple.OptionParser.parse(OptionParser.java:396)
	at kafka.admin.TopicCommand$TopicCommandOptions.<init>(TopicCommand.scala:352)
	at kafka.admin.TopicCommand$.main(TopicCommand.scala:44)
	at kafka.admin.TopicCommand.main(TopicCommand.scala)
Exception in thread "main" joptsimple.UnrecognizedOptionException: config cleanup.policy is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
	at joptsimple.OptionParser.parse(OptionParser.java:396)
	at kafka.admin.TopicCommand$TopicCommandOptions.<init>(TopicCommand.scala:352)
	at kafka.admin.TopicCommand$.main(TopicCommand.scala:44)
	at kafka.admin.TopicCommand.main(TopicCommand.scala)
Created topic "test-topic".
```

I am pulling the latest image from dockerhub and I know this was working a few weeks ago, [has a recent change broken something](https://github.com/wurstmeister/kafka-docker/pull/226/files)?

Manually creating the topic works fine:
```
bash-4.3# $KAFKA_HOME/bin/kafka-topics.sh --create --zookeeper $KAFKA_ZOOKEEPER_CONNECT --replication-factor 1 --partitions 2 --topic "compact-test-no-offset" --config cleanup.policy=compact --if-not-exists
Created topic "compact-test-no-offset".
```

Any thoughts?

**Comment by robbmj-index-exchange** [comment]
After reverting back to the 1.0.0 version of `create-topics.sh`, the compacted topics are created.

```
creating topics: test-topic:2:1
Created topic "test-topic".
[2018-01-13 18:01:17,436] INFO [ReplicaFetcherManager on broker 1001] Removed fetcher for partitions test-topic-0,test-topic-1 (kafka.server.ReplicaFetcherManager)
[2018-01-13 18:01:17,486] INFO Loading producer state from offset 0 for partition test-topic-0 with message format version 2 (kafka.log.Log)
[2018-01-13 18:01:17,499] INFO Completed load of log test-topic-0 with 1 log segments, log start offset 0 and log end offset 0 in 34 ms (kafka.log.Log)
[2018-01-13 18:01:17,507] INFO Created log for partition [test-topic,0] in /kafka/kafka-logs-idb-kafka with properties {compression.type -> producer, message.format.version -> 1.0-IV0, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> [delete], flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 604800000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
[2018-01-13 18:01:17,508] INFO [Partition test-topic-0 broker=1001] No checkpointed highwatermark is found for partition test-topic-0 (kafka.cluster.Partition)
[2018-01-13 18:01:17,511] INFO Replica loaded for partition test-topic-0 with initial high watermark 0 (kafka.cluster.Replica)
[2018-01-13 18:01:17,513] INFO [Partition test-topic-0 broker=1001] test-topic-0 starts at Leader Epoch 0 from offset 0. Previous Leader Epoch was: -1 (kafka.cluster.Partition)
[2018-01-13 18:01:17,535] INFO Loading producer state from offset 0 for partition test-topic-1 with message format version 2 (kafka.log.Log)
[2018-01-13 18:01:17,536] INFO Completed load of log test-topic-1 with 1 log segments, log start offset 0 and log end offset 0 in 1 ms (kafka.log.Log)
[2018-01-13 18:01:17,537] INFO Created log for partition [test-topic,1] in /kafka/kafka-logs-idb-kafka with properties {compression.type -> producer, message.format.version -> 1.0-IV0, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> [delete], flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 604800000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
[2018-01-13 18:01:17,537] INFO [Partition test-topic-1 broker=1001] No checkpointed highwatermark is found for partition test-topic-1 (kafka.cluster.Partition)
[2018-01-13 18:01:17,537] INFO Replica loaded for partition test-topic-1 with initial high watermark 0 (kafka.cluster.Replica)
[2018-01-13 18:01:17,537] INFO [Partition test-topic-1 broker=1001] test-topic-1 starts at Leader Epoch 0 from offset 0. Previous Leader Epoch was: -1 (kafka.cluster.Partition)
creating topics: fact-artifact-request:2:1:compact
Created topic "fact-artifact-request".
[2018-01-13 18:01:19,201] INFO [ReplicaFetcherManager on broker 1001] Removed fetcher for partitions fact-artifact-request-1,fact-artifact-request-0 (kafka.server.ReplicaFetcherManager)
[2018-01-13 18:01:19,206] INFO Loading producer state from offset 0 for partition fact-artifact-request-1 with message format version 2 (kafka.log.Log)
[2018-01-13 18:01:19,207] INFO Completed load of log fact-artifact-request-1 with 1 log segments, log start offset 0 and log end offset 0 in 1 ms (kafka.log.Log)
[2018-01-13 18:01:19,208] INFO Created log for partition [fact-artifact-request,1] in /kafka/kafka-logs-idb-kafka with properties {compression.type -> producer, message.format.version -> 1.0-IV0, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> compact, flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 604800000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
[2018-01-13 18:01:19,209] INFO [Partition fact-artifact-request-1 broker=1001] No checkpointed highwatermark is found for partition fact-artifact-request-1 (kafka.cluster.Partition)
[2018-01-13 18:01:19,209] INFO Replica loaded for partition fact-artifact-request-1 with initial high watermark 0 (kafka.cluster.Replica)
[2018-01-13 18:01:19,209] INFO [Partition fact-artifact-request-1 broker=1001] fact-artifact-request-1 starts at Leader Epoch 0 from offset 0. Previous Leader Epoch was: -1 (kafka.cluster.Partition)
[2018-01-13 18:01:19,214] INFO Loading producer state from offset 0 for partition fact-artifact-request-0 with message format version 2 (kafka.log.Log)
[2018-01-13 18:01:19,215] INFO Completed load of log fact-artifact-request-0 with 1 log segments, log start offset 0 and log end offset 0 in 2 ms (kafka.log.Log)
[2018-01-13 18:01:19,220] INFO Created log for partition [fact-artifact-request,0] in /kafka/kafka-logs-idb-kafka with properties {compression.type -> producer, message.format.version -> 1.0-IV0, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> compact, flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 604800000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
[2018-01-13 18:01:19,221] INFO [Partition fact-artifact-request-0 broker=1001] No checkpointed highwatermark is found for partition fact-artifact-request-0 (kafka.cluster.Partition)
[2018-01-13 18:01:19,221] INFO Replica loaded for partition fact-artifact-request-0 with initial high watermark 0 (kafka.cluster.Replica)
[2018-01-13 18:01:19,221] INFO [Partition fact-artifact-request-0 broker=1001] fact-artifact-request-0 starts at Leader Epoch 0 from offset 0. Previous Leader Epoch was: -1 (kafka.cluster.Partition)

▽
creating topics: fact-artifact-update:2:1:compact
Created topic "fact-artifact-update".
[2018-01-13 18:01:21,043] INFO [ReplicaFetcherManager on broker 1001] Removed fetcher for partitions fact-artifact-update-1,fact-artifact-update-0 (kafka.server.ReplicaFetcherManager)
[2018-01-13 18:01:21,051] INFO Loading producer state from offset 0 for partition fact-artifact-update-1 with message format version 2 (kafka.log.Log)
[2018-01-13 18:01:21,052] INFO Completed load of log fact-artifact-update-1 with 1 log segments, log start offset 0 and log end offset 0 in 2 ms (kafka.log.Log)
[2018-01-13 18:01:21,053] INFO Created log for partition [fact-artifact-update,1] in /kafka/kafka-logs-idb-kafka with properties {compression.type -> producer, message.format.version -> 1.0-IV0, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> compact, flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 604800000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
[2018-01-13 18:01:21,053] INFO [Partition fact-artifact-update-1 broker=1001] No checkpointed highwatermark is found for partition fact-artifact-update-1 (kafka.cluster.Partition)
[2018-01-13 18:01:21,057] INFO Replica loaded for partition fact-artifact-update-1 with initial high watermark 0 (kafka.cluster.Replica)
[2018-01-13 18:01:21,057] INFO [Partition fact-artifact-update-1 broker=1001] fact-artifact-update-1 starts at Leader Epoch 0 from offset 0. Previous Leader Epoch was: -1 (kafka.cluster.Partition)
[2018-01-13 18:01:21,065] INFO Loading producer state from offset 0 for partition fact-artifact-update-0 with message format version 2 (kafka.log.Log)
[2018-01-13 18:01:21,066] INFO Completed load of log fact-artifact-update-0 with 1 log segments, log start offset 0 and log end offset 0 in 2 ms (kafka.log.Log)
[2018-01-13 18:01:21,067] INFO Created log for partition [fact-artifact-update,0] in /kafka/kafka-logs-idb-kafka with properties {compression.type -> producer, message.format.version -> 1.0-IV0, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> compact, flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 604800000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
[2018-01-13 18:01:21,067] INFO [Partition fact-artifact-update-0 broker=1001] No checkpointed highwatermark is found for partition fact-artifact-update-0 (kafka.cluster.Partition)
[2018-01-13 18:01:21,067] INFO Replica loaded for partition fact-artifact-update-0 with initial high watermark 0 (kafka.cluster.Replica)
[2018-01-13 18:01:21,068] INFO [Partition fact-artifact-update-0 broker=1001] fact-artifact-update-0 starts at Leader Epoch 0 from offset 0. Previous Leader Epoch was: -1 (kafka.cluster.Partition)
creating topics: commit-log:2:1:compact
Created topic "commit-log".
[2018-01-13 18:01:22,854] INFO [ReplicaFetcherManager on broker 1001] Removed fetcher for partitions commit-log-0,commit-log-1 (kafka.server.ReplicaFetcherManager)
[2018-01-13 18:01:22,858] INFO Loading producer state from offset 0 for partition commit-log-0 with message format version 2 (kafka.log.Log)
[2018-01-13 18:01:22,858] INFO Completed load of log commit-log-0 with 1 log segments, log start offset 0 and log end offset 0 in 1 ms (kafka.log.Log)
[2018-01-13 18:01:22,860] INFO Created log for partition [commit-log,0] in /kafka/kafka-logs-idb-kafka with properties {compression.type -> producer, message.format.version -> 1.0-IV0, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> compact, flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 604800000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
[2018-01-13 18:01:22,861] INFO [Partition commit-log-0 broker=1001] No checkpointed highwatermark is found for partition commit-log-0 (kafka.cluster.Partition)
[2018-01-13 18:01:22,861] INFO Replica loaded for partition commit-log-0 with initial high watermark 0 (kafka.cluster.Replica)
[2018-01-13 18:01:22,861] INFO [Partition commit-log-0 broker=1001] commit-log-0 starts at Leader Epoch 0 from offset 0. Previous Leader Epoch was: -1 (kafka.cluster.Partition)
[2018-01-13 18:01:22,865] INFO Loading producer state from offset 0 for partition commit-log-1 with message format version 2 (kafka.log.Log)
[2018-01-13 18:01:22,876] INFO Completed load of log commit-log-1 with 1 log segments, log start offset 0 and log end offset 0 in 11 ms (kafka.log.Log)
[2018-01-13 18:01:22,877] INFO Created log for partition [commit-log,1] in /kafka/kafka-logs-idb-kafka with properties {compression.type -> producer, message.format.version -> 1.0-IV0, file.delete.delay.ms -> 60000, max.message.bytes -> 1000012, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, min.insync.replicas -> 1, segment.jitter.ms -> 0, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, cleanup.policy -> compact, flush.ms -> 9223372036854775807, segment.ms -> 604800000, segment.bytes -> 1073741824, retention.ms -> 604800000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760, flush.messages -> 9223372036854775807}. (kafka.log.LogManager)
[2018-01-13 18:01:22,878] INFO [Partition commit-log-1 broker=1001] No checkpointed highwatermark is found for partition commit-log-1 (kafka.cluster.Partition)
[2018-01-13 18:01:22,878] INFO Replica loaded for partition commit-log-1 with initial high watermark 0 (kafka.cluster.Replica)
[2018-01-13 18:01:22,878] INFO [Partition commit-log-1 broker=1001] commit-log-1 starts at Leader Epoch 0 from offset 0. Previous Leader Epoch was: -1 (kafka.cluster.Partition)
```

```
bash-4.3# $KAFKA_HOME/bin/kafka-topics.sh --zookeeper inventorydb-kafka-zookeeper:2181 --list
commit-log
fact-artifact-request
fact-artifact-update
test-topic
```

This pull: https://github.com/wurstmeister/kafka-docker/pull/226/files has introduced a regression

**Comment by sscaling** [comment]
If you observe the kafka logs, you will see the following exception

```
Exception in thread "main" joptsimple.UnrecognizedOptionException: config cleanup.policy is not a recognized option
kafka_2         | Exception in thread "main" joptsimple.UnrecognizedOptionException: config cleanup.policy is not a recognized option
kafka_1         |        at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
kafka_2         |        at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
kafka_1         |        at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
kafka_2         |        at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
kafka_1         |        at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
kafka_2         |        at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
kafka_1         |        at joptsimple.OptionParser.parse(OptionParser.java:396)
kafka_2         |        at joptsimple.OptionParser.parse(OptionParser.java:396)
kafka_2         |        at kafka.admin.TopicCommand$TopicCommandOptions.<init>(TopicCommand.scala:352)
kafka_1         |        at kafka.admin.TopicCommand$TopicCommandOptions.<init>(TopicCommand.scala:352)
kafka_2         |        at kafka.admin.TopicCommand$.main(TopicCommand.scala:44)
kafka_1         |        at kafka.admin.TopicCommand$.main(TopicCommand.scala:44)
kafka_2         |        at kafka.admin.TopicCommand.main(TopicCommand.scala)
kafka_1         |        at kafka.admin.TopicCommand.main(TopicCommand.scala)
```
