### ISSUE TITLE
Kafka cannot connect to zookeeper in swarm mode when hostname is provided but connects well with IP

### ISSUE THREAD

**Issue by lastakhov** [wurstmeister/kafka-docker#249]
Hi. 

I'm trying to setup swarm Kafka + Zookeeper. On one swarm manager node first. Looks very simple but I encountered a problem with Kafka to Zookeeper connection. 

my compose file is:

```
version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - target: 2181
        published: 2181
        protocol: tcp
        mode: ingress
  kafka:
    image: wurstmeister/kafka
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: ingress
    depends_on: 
     - zookeeper
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_HOST_NAME:
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
 ```

when I'm trying to create a stack with ingress network in swarm it looks alright. 
Zookeeper starts well and wait for connection. 
Kafka is resolving zookeeper hostname to correct IP address and trying to connect. It successfully connects and establishes the session but after that immediately closes this session end exits. Zookeeper log also shows that connection was established but closed just after. 

If I set  KAFKA_ZOOKEEPER_CONNECT: 10.0.4.4:2181  (the same resolved IP) then it works fine. Everything connects and starts up. What could be a problem here?

Here is the log from Kafka:

```
[2018-01-16 12:41:45,392] INFO KafkaConfig values: 
	advertised.host.name = null
	advertised.listeners = OUTSIDE://lvastakhov-HP-ProDesk-400-G2-MT:9094,INSIDE://:9092
	advertised.port = null
	alter.config.policy.class.name = null
	authorizer.class.name = 
	auto.create.topics.enable = true
	auto.leader.rebalance.enable = true
	background.threads = 10
	broker.id = -1
	broker.id.generation.enable = true
	broker.rack = null
	compression.type = producer
	connections.max.idle.ms = 600000
	controlled.shutdown.enable = true
	controlled.shutdown.max.retries = 3
	controlled.shutdown.retry.backoff.ms = 5000
	controller.socket.timeout.ms = 30000
	create.topic.policy.class.name = null
	default.replication.factor = 1
	delete.records.purgatory.purge.interval.requests = 1
	delete.topic.enable = true
	fetch.purgatory.purge.interval.requests = 1000
	group.initial.rebalance.delay.ms = 0
	group.max.session.timeout.ms = 300000
	group.min.session.timeout.ms = 6000
	host.name = 
	inter.broker.listener.name = INSIDE
	inter.broker.protocol.version = 1.0-IV0
	leader.imbalance.check.interval.seconds = 300
	leader.imbalance.per.broker.percentage = 10
	listener.security.protocol.map = INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
	listeners = OUTSIDE://:9094,INSIDE://:9092
	log.cleaner.backoff.ms = 15000
	log.cleaner.dedupe.buffer.size = 134217728
	log.cleaner.delete.retention.ms = 86400000
	log.cleaner.enable = true
	log.cleaner.io.buffer.load.factor = 0.9
	log.cleaner.io.buffer.size = 524288
	log.cleaner.io.max.bytes.per.second = 1.7976931348623157E308
	log.cleaner.min.cleanable.ratio = 0.5
	log.cleaner.min.compaction.lag.ms = 0
	log.cleaner.threads = 1
	log.cleanup.policy = [delete]
	log.dir = /tmp/kafka-logs
	log.dirs = /kafka/kafka-logs-d6a4a54496f0
	log.flush.interval.messages = 9223372036854775807
	log.flush.interval.ms = null
	log.flush.offset.checkpoint.interval.ms = 60000
	log.flush.scheduler.interval.ms = 9223372036854775807
	log.flush.start.offset.checkpoint.interval.ms = 60000
	log.index.interval.bytes = 4096
	log.index.size.max.bytes = 10485760
	log.message.format.version = 1.0-IV0
	log.message.timestamp.difference.max.ms = 9223372036854775807
	log.message.timestamp.type = CreateTime
	log.preallocate = false
	log.retention.bytes = -1
	log.retention.check.interval.ms = 300000
	log.retention.hours = 168
	log.retention.minutes = null
	log.retention.ms = null
	log.roll.hours = 168
	log.roll.jitter.hours = 0
	log.roll.jitter.ms = null
	log.roll.ms = null
	log.segment.bytes = 1073741824
	log.segment.delete.delay.ms = 60000
	max.connections.per.ip = 2147483647
	max.connections.per.ip.overrides = 
	message.max.bytes = 1000012
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	min.insync.replicas = 1
	num.io.threads = 8
	num.network.threads = 3
	num.partitions = 1
	num.recovery.threads.per.data.dir = 1
	num.replica.fetchers = 1
	offset.metadata.max.bytes = 4096
	offsets.commit.required.acks = -1
	offsets.commit.timeout.ms = 5000
	offsets.load.buffer.size = 5242880
	offsets.retention.check.interval.ms = 600000
	offsets.retention.minutes = 1440
	offsets.topic.compression.codec = 0
	offsets.topic.num.partitions = 50
	offsets.topic.replication.factor = 1
	offsets.topic.segment.bytes = 104857600

9092
	principal.builder.class = null
	producer.purgatory.purge.interval.requests = 1000
	queued.max.request.bytes = -1
	queued.max.requests = 500
	quota.consumer.default = 9223372036854775807
	quota.producer.default = 9223372036854775807
	quota.window.num = 11
	quota.window.size.seconds = 1
	replica.fetch.backoff.ms = 1000
	replica.fetch.max.bytes = 1048576
	replica.fetch.min.bytes = 1
	replica.fetch.response.max.bytes = 10485760
	replica.fetch.wait.max.ms = 500
	replica.high.watermark.checkpoint.interval.ms = 5000
	replica.lag.time.max.ms = 10000
	replica.socket.receive.buffer.bytes = 65536
	replica.socket.timeout.ms = 30000
	replication.quota.window.num = 11
	replication.quota.window.size.seconds = 1
	request.timeout.ms = 30000
	reserved.broker.max.id = 1000
	sasl.enabled.mechanisms = [GSSAPI]
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.principal.to.local.rules = [DEFAULT]
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism.inter.broker.protocol = GSSAPI
	security.inter.broker.protocol = PLAINTEXT
	socket.receive.buffer.bytes = 102400
	socket.request.max.bytes = 104857600
	socket.send.buffer.bytes = 102400
	ssl.cipher.suites = null
	ssl.client.auth = none
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	transaction.abort.timed.out.transaction.cleanup.interval.ms = 60000
	transaction.max.timeout.ms = 900000
	transaction.remove.expired.transaction.cleanup.interval.ms = 3600000
	transaction.state.log.load.buffer.size = 5242880
	transaction.state.log.min.isr = 1
	transaction.state.log.num.partitions = 50
	transaction.state.log.replication.factor = 1
	transaction.state.log.segment.bytes = 104857600
	transactional.id.expiration.ms = 604800000
	unclean.leader.election.enable = false
	zookeeper.connect = zookeeper:2181
	zookeeper.connection.timeout.ms = 6000
	zookeeper.session.timeout.ms = 6000
	zookeeper.set.acl = false
	zookeeper.sync.time.ms = 2000
 (kafka.server.KafkaConfig)
[2018-01-16 12:41:45,516] INFO starting (kafka.server.KafkaServer)
[2018-01-16 12:41:45,621] INFO Connecting to zookeeper on zookeeper:2181 (kafka.server.KafkaServer)
[2018-01-16 12:41:45,687] INFO Starting ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2018-01-16 12:41:45,694] INFO Client environment:zookeeper.version=3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f, built on 03/23/2017 10:13 GMT (org.apache.zookeeper.ZooKeeper)
[2018-01-16 12:41:45,694] INFO Client environment:host.name=d6a4a54496f0 (org.apache.zookeeper.ZooKeeper)
[2018-01-16 12:41:45,694] INFO Client environment:java.version=1.8.0_152 (org.apache.zookeeper.ZooKeeper)
[2018-01-16 12:41:45,694] INFO Client environment:java.vendor=Oracle Corporation (org.apache.zookeeper.ZooKeeper)
[2018-01-16 12:41:45,694] INFO Client environment:java.home=/opt/jdk1.8.0_152/jre (org.apache.zookeeper.ZooKeeper)
[2018-01-16 12:41:45,694] INFO Client environment:java.class.path=:/opt/kafka/bin/../libs/aopalliance-repackaged-2.5.0-b32.jar:/opt/kafka/bin/../libs/argparse4j-0.7.0.jar:/opt/kafka/bin/../libs/commons-lang3-3.5.jar:/opt/kafka/bin/../libs/connect-api-1.0.0.jar:/opt/kafka/bin/../libs/connect-file-1.0.0.jar:/opt/kafka/bin/../libs/connect-json-1.0.0.jar:/opt/kafka/bin/../libs/connect-runtime-1.0.0.jar:/opt/kafka/bin/../libs/connect-transforms-1.0.0.jar:/opt/kafka/bin/../libs/guava-20.0.jar:/opt/kafka/bin/../libs/hk2-api-2.5.0-b32.jar:/opt/kafka/bin/../libs/hk2-locator-2.5.0-b32.jar:/opt/kafka/bin/../libs/hk2-utils-2.5.0-b32.jar:/opt/kafka/bin/../libs/jackson-annotations-2.9.1.jar:/opt/kafka/bin/../libs/jackson-core-2.9.1.jar:/opt/kafka/bin/../libs/jackson-databind-2.9.1.jar:/opt/kafka/bin/../libs/jackson-jaxrs-base-2.9.1.jar:/opt/kafka/bin/../libs/jackson-jaxrs-json-provider-2.9.1.jar:/opt/kafka/bin/../libs/jackson-module-jaxb-annotations-2.9.1.jar:/opt/kafka/bin/../libs/javassist-3.20.0-GA.jar:/opt/kafka/bin/../libs/javassist-3.21.0-GA.jar:/opt/kafka/bin/../libs/javax.annotation-api-1.2.jar:/opt/kafka/bin/../libs/javax.inject-1.jar:/opt/kafka/bin/../libs/javax.inject-2.5.0-b32.jar:/opt/kafka/bin/../libs/javax.servlet-api-3.1.0.jar:/opt/kafka/bin/../libs/javax.ws.rs-api-2.0.1.jar:/opt/kafka/bin/../libs/jersey-client-2.25.1.jar:/opt/kafka/bin/../libs/jersey-common-2.25.1.jar:/opt/kafka/bin/../libs/jersey-container-servlet-2.25.1.jar:/opt/kafka/bin/../libs/jersey-container-servlet-core-2.25.1.jar:/opt/kafka/bin/../libs/jersey-guava-2.25.1.jar:/opt/kafka/bin/../libs/jersey-media-jaxb-2.25.1.jar:/opt/kafka/bin/../libs/jersey-server-2.25.1.jar:/opt/kafka/bin/../libs/jetty-continuation-9.2.22.v20170606.jar:/opt/kafka/bin/../libs/jetty-http-9.2.22.v20170606.jar:/opt/kafka/bin/../libs/jetty-io-9.2.22.v20170606.jar:/opt/kafka/bin/../libs/jetty-security-9.2.22.v20170606.jar:/opt/kafka/bin/../libs/jetty-server-9.2.22.v20170606.jar:/opt/kafka/bin/../libs/jetty-servlet-9.2.22.v20170606.jar:/opt/kafka/bin/../libs/jetty-servlets-9.2.22.v20170606.jar:/opt/kafka/bin/../libs/jetty-util-9.2.22.v20170606.jar:/opt/kafka/bin/../libs/jopt-simple-5.0.4.jar:/opt/kafka/bin/../libs/kafka-clients-1.0.0.jar:/opt/kafka/bin/../libs/kafka-log4j-appender-1.0.0.jar:/opt/kafka/bin/../libs/kafka-streams-1.0.0.jar:/opt/kafka/bin/../libs/kafka-streams-examples-1.0.0.jar:/opt/kafka/bin/../libs/kafka-tools-1.0.0.jar:/opt/kafka/bin/../libs/kafka_2.12-1.0.0-sources.jar:/opt/kafka/bin/../libs/kafka_2.12-1.0.0-test-sources.jar:/opt/kafka/bin/../libs/kafka_2.12-1.0.0.jar:/opt/kafka/bin/../libs/log4j-1.2.17.jar:/opt/kafka/bin/../libs/lz4-java-1.4.jar:/opt/kafka/bin/../libs/maven-artifact-3.5.0.jar:/opt/kafka/bin/../libs/metrics-core-2.2.0.jar:/opt/kafka/bin/../libs/osgi-resource-locator-1.0.1.jar:/opt/kafka/bin/../libs/plexus-utils-3.0.24.jar:/opt/kafka/bin/../libs/reflections-0.9.11.jar:/opt/kafka/bin/../libs/rocksdbjni-5.7.3.jar:/opt/kafka/bin/../libs/scala-library-2.12.3.jar:/opt/kafka/bin/../libs/slf4j-api-1.7.25.jar:/opt/kafka/bin/../libs/slf4j-log4j12-1.7.25.jar:/opt/kafka/bin/../libs/snappy-java-1.1.4.jar:/opt/kafka/bin/../libs/validation-api-1.1.0.Final.jar:/opt/kafka/bin/../libs/zkclient-0.10.jar:/opt/kafka/bin/../libs/zookeeper-3.4.10.jar (org.apache.zookeeper.ZooKeeper)
[2018-01-16 12:41:45,694] INFO Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib (org.apache.zookeeper.ZooKeeper)
[2018-01-16 12:41:45,694] INFO Client environment:java.io.tmpdir=/tmp (org.apache.zookeeper.ZooKeeper)
[2018-01-16 12:41:45,694] INFO Client environment:java.compiler=<NA> (org.apache.zookeeper.ZooKeeper)
[2018-01-16 12:41:45,694] INFO Client environment:os.name=Linux (org.apache.zookeeper.ZooKeeper)
[2018-01-16 12:41:45,694] INFO Client environment:os.arch=amd64 (org.apache.zookeeper.ZooKeeper)
[2018-01-16 12:41:45,694] INFO Client environment:os.version=4.10.0-42-generic (org.apache.zookeeper.ZooKeeper)
[2018-01-16 12:41:45,695] INFO Client environment:user.name=root (org.apache.zookeeper.ZooKeeper)
[2018-01-16 12:41:45,695] INFO Client environment:user.home=/root (org.apache.zookeeper.ZooKeeper)
[2018-01-16 12:41:45,695] INFO Client environment:user.dir=/ (org.apache.zookeeper.ZooKeeper)
[2018-01-16 12:41:45,695] INFO Initiating client connection, connectString=zookeeper:2181 sessionTimeout=6000 watcher=org.I0Itec.zkclient.ZkClient@4690b489 (org.apache.zookeeper.ZooKeeper)
[2018-01-16 12:41:45,742] INFO Waiting for keeper state SyncConnected (org.I0Itec.zkclient.ZkClient)
[2018-01-16 12:41:51,743] INFO Terminate ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2018-01-16 12:41:55,763] INFO Opening socket connection to server 10.0.4.4/10.0.4.4:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-01-16 12:41:55,810] INFO Socket connection established to 10.0.4.4/10.0.4.4:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2018-01-16 12:41:55,919] INFO Session establishment complete on server 10.0.4.4/10.0.4.4:2181, sessionid = 0x160fefcda440000, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
[2018-01-16 12:41:55,975] INFO Session: 0x160fefcda440000 closed (org.apache.zookeeper.ZooKeeper)
[2018-01-16 12:41:55,977] INFO EventThread shut down for session: 0x160fefcda440000 (org.apache.zookeeper.ClientCnxn)
[2018-01-16 12:41:55,977] FATAL Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server 'zookeeper:2181' with timeout of 6000 ms
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1233)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:157)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:131)
	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:115)
	at kafka.utils.ZkUtils$.withMetrics(ZkUtils.scala:92)
	at kafka.server.KafkaServer.initZk(KafkaServer.scala:350)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:194)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:92)
	at kafka.Kafka.main(Kafka.scala)
[2018-01-16 12:41:56,030] INFO shutting down (kafka.server.KafkaServer)
[2018-01-16 12:41:56,073] INFO shut down completed (kafka.server.KafkaServer)
[2018-01-16 12:41:56,074] FATAL Exiting Kafka. (kafka.server.KafkaServerStartable)
[2018-01-16 12:41:56,103] INFO shutting down (kafka.server.KafkaServer)
```

At the same time Zookeeper side says:

```
2018-01-16 12:41:11,861 [myid:] - INFO  [main:QuorumPeerConfig@124] - Reading configuration from: /opt/zookeeper-3.4.9/bin/../conf/zoo.cfg
2018-01-16 12:41:11,900 [myid:] - INFO  [main:DatadirCleanupManager@78] - autopurge.snapRetainCount set to 3
2018-01-16 12:41:11,900 [myid:] - INFO  [main:DatadirCleanupManager@79] - autopurge.purgeInterval set to 1
2018-01-16 12:41:11,900 [myid:] - WARN  [main:QuorumPeerMain@113] - Either no config or no quorum defined in config, running  in standalone mode
2018-01-16 12:41:11,900 [myid:] - INFO  [PurgeTask:DatadirCleanupManager$PurgeTask@138] - Purge task started.
2018-01-16 12:41:11,936 [myid:] - INFO  [PurgeTask:DatadirCleanupManager$PurgeTask@144] - Purge task completed.
2018-01-16 12:41:11,939 [myid:] - INFO  [main:QuorumPeerConfig@124] - Reading configuration from: /opt/zookeeper-3.4.9/bin/../conf/zoo.cfg
2018-01-16 12:41:11,942 [myid:] - INFO  [main:ZooKeeperServerMain@96] - Starting server
2018-01-16 12:41:11,961 [myid:] - INFO  [main:Environment@100] - Server environment:zookeeper.version=3.4.9-1757313, built on 08/23/2016 06:50 GMT
2018-01-16 12:41:11,961 [myid:] - INFO  [main:Environment@100] - Server environment:host.name=b6e697736faa
2018-01-16 12:41:11,961 [myid:] - INFO  [main:Environment@100] - Server environment:java.version=1.7.0_65
2018-01-16 12:41:11,961 [myid:] - INFO  [main:Environment@100] - Server environment:java.vendor=Oracle Corporation
2018-01-16 12:41:11,961 [myid:] - INFO  [main:Environment@100] - Server environment:java.home=/usr/lib/jvm/java-7-openjdk-amd64/jre
2018-01-16 12:41:11,961 [myid:] - INFO  [main:Environment@100] - Server environment:java.class.path=/opt/zookeeper-3.4.9/bin/../build/classes:/opt/zookeeper-3.4.9/bin/../build/lib/*.jar:/opt/zookeeper-3.4.9/bin/../lib/slf4j-log4j12-1.6.1.jar:/opt/zookeeper-3.4.9/bin/../lib/slf4j-api-1.6.1.jar:/opt/zookeeper-3.4.9/bin/../lib/netty-3.10.5.Final.jar:/opt/zookeeper-3.4.9/bin/../lib/log4j-1.2.16.jar:/opt/zookeeper-3.4.9/bin/../lib/jline-0.9.94.jar:/opt/zookeeper-3.4.9/bin/../zookeeper-3.4.9.jar:/opt/zookeeper-3.4.9/bin/../src/java/lib/*.jar:/opt/zookeeper-3.4.9/bin/../conf:
2018-01-16 12:41:11,961 [myid:] - INFO  [main:Environment@100] - Server environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
2018-01-16 12:41:11,961 [myid:] - INFO  [main:Environment@100] - Server environment:java.io.tmpdir=/tmp
2018-01-16 12:41:11,963 [myid:] - INFO  [main:Environment@100] - Server environment:java.compiler=<NA>
2018-01-16 12:41:11,963 [myid:] - INFO  [main:Environment@100] - Server environment:os.name=Linux
2018-01-16 12:41:11,963 [myid:] - INFO  [main:Environment@100] - Server environment:os.arch=amd64
2018-01-16 12:41:11,963 [myid:] - INFO  [main:Environment@100] - Server environment:os.version=4.10.0-42-generic
2018-01-16 12:41:11,963 [myid:] - INFO  [main:Environment@100] - Server environment:user.name=root
2018-01-16 12:41:11,963 [myid:] - INFO  [main:Environment@100] - Server environment:user.home=/root
2018-01-16 12:41:11,963 [myid:] - INFO  [main:Environment@100] - Server environment:user.dir=/opt/zookeeper-3.4.9
2018-01-16 12:41:11,965 [myid:] - INFO  [main:ZooKeeperServer@815] - tickTime set to 2000
2018-01-16 12:41:11,965 [myid:] - INFO  [main:ZooKeeperServer@824] - minSessionTimeout set to -1
2018-01-16 12:41:11,965 [myid:] - INFO  [main:ZooKeeperServer@833] - maxSessionTimeout set to -1
2018-01-16 12:41:11,993 [myid:] - INFO  [main:NIOServerCnxnFactory@89] - binding to port 0.0.0.0/0.0.0.0:2181
2018-01-16 12:41:55,811 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /10.0.4.7:34196
2018-01-16 12:41:55,817 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@928] - Client attempting to establish new session at /10.0.4.7:34196
2018-01-16 12:41:55,820 [myid:] - INFO  [SyncThread:0:FileTxnLog@203] - Creating new log file: log.1
2018-01-16 12:41:55,916 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@673] - Established session 0x160fefcda440000 with negotiated timeout 6000 for client /10.0.4.7:34196
2018-01-16 12:41:55,922 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@487] - Processed session termination for sessionid: 0x160fefcda440000
2018-01-16 12:41:55,976 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1008] - Closed socket connection for client /10.0.4.7:34196 which had sessionid 0x160fefcda440000
```

**Comment by manalibhutiyani** [comment]
I am facing a similar issue on my multi-node K8s setup with the `wurstmeister/kafka-docker` image.

**Comment by sscaling** [comment]
@lastakhov - a few comments / questions

* Is zookeeper port accessible from the kafka container? `org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server 'zookeeper:2181' with timeout of 6000 ms` would indicate that it's not.
* Have you got this working using the notes in the Readme and the example docker-compose-swarm.yml first?

**Comment by lastakhov** [comment]
I got this thing working. Don't know why but in swarm mode this takes longer t han 6000 ms. I just set timeout for zookeeper connection to 16000 ms and it worked. 
KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 16000

**Comment by saule1508** [comment]
I have the same issue in case there is no internet access on the host: in this case I noticed that docker swarm does requests to 8.8.8.8 for ipv6, those requests time-out and so does the kafka/zookeeper connection. I had to put KAFKA_ZOOKEEPER_TIMEOUT_MS to 36000

**Comment by scne** [comment]
I've the same problem with kubernetes

**kafka-deployment.yml**
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-broker
  labels:
    app: kafka
    component: kafka-broker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        component: kafka-broker
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:0.10.1.0
        ports:
        - containerPort: 9092
        env:
          - name: ENABLE_AUTO_EXTEND
            value: "true"
          - name: KAFKA_RESERVED_BROKER_MAX_ID
            value: "9"
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "false"
          - name: KAFKA_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: kafka-zk:2181
          - name: KAFKA_ZOOKEEPER_TIMEOUT_MS
            value: 1600
```

**kafka-zk-deployment.yml**

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-zk
  labels:
    app: kafka
    component: kafka-zk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-zk
        component: kafka-zk
    spec:
      containers:
      - name: kafka-zk
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: kafka-zk
```

But KAFKA_ZOOKEEPER_TIMEOUT_MS not change

```
...
zookeeper.connect = kafka-zk:2181
	zookeeper.connection.timeout.ms = 6000
	zookeeper.session.timeout.ms = 6000
	zookeeper.set.acl = false
	zookeeper.sync.time.ms = 2000
 (kafka.server.KafkaConfig)
[2018-06-19 13:12:36,415] INFO starting (kafka.server.KafkaServer)
[2018-06-19 13:12:36,429] INFO [ThrottledRequestReaper-Fetch], Starting  (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[2018-06-19 13:12:36,431] INFO [ThrottledRequestReaper-Produce], Starting  (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[2018-06-19 13:12:36,434] INFO Connecting to zookeeper on kafka-zk:2181 (kafka.server.KafkaServer)
[2018-06-19 13:12:36,450] INFO Starting ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2018-06-19 13:12:36,457] INFO Client environment:zookeeper.version=3.4.8--1, built on 02/06/2016 03:18 GMT (org.apache.zookeeper.ZooKeeper)
[2018-06-19 13:12:36,457] INFO Client environment:host.name=kafka-broker-6bc7d7944b-vcvgl (org.apache.zookeeper.ZooKeeper)
[2018-06-19 13:12:36,457] INFO Client environment:java.version=1.8.0_102 (org.apache.zookeeper.ZooKeeper)
.......
[2018-06-19 13:12:36,459] INFO Initiating client connection, connectString=kafka-zk:2181 sessionTimeout=6000 watcher=org.I0Itec.zkclient.ZkClient@6ca8564a (org.apache.zookeeper.ZooKeeper)
waiting for kafka to be ready
[2018-06-19 13:12:46,057] INFO Waiting for keeper state SyncConnected (org.I0Itec.zkclient.ZkClient)
[2018-06-19 13:12:52,058] INFO Terminate ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
waiting for kafka to be ready
waiting for kafka to be ready
[2018-06-19 13:13:06,075] INFO Opening socket connection to server kafka-zk.default.svc.cluster.local/10.103.156.248:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-06-19 13:13:06,143] INFO Socket connection established to kafka-zk.default.svc.cluster.local/10.103.156.248:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2018-06-19 13:13:06,153] INFO Session establishment complete on server kafka-zk.default.svc.cluster.local/10.103.156.248:2181, sessionid = 0x1641825a8dc0006, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
[2018-06-19 13:13:06,162] INFO Session: 0x1641825a8dc0006 closed (org.apache.zookeeper.ZooKeeper)
[2018-06-19 13:13:06,164] INFO EventThread shut down for session: 0x1641825a8dc0006 (org.apache.zookeeper.ClientCnxn)
[2018-06-19 13:13:06,163] FATAL Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 6000
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1232)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:156)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:130)
	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:76)
	at kafka.utils.ZkUtils$.apply(ZkUtils.scala:58)
	at kafka.server.KafkaServer.initZk(KafkaServer.scala:327)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:200)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:39)
	at kafka.Kafka$.main(Kafka.scala:67)
	at kafka.Kafka.main(Kafka.scala)
[2018-06-19 13:13:06,166] INFO shutting down (kafka.server.KafkaServer)
[2018-06-19 13:13:06,170] INFO shut down completed (kafka.server.KafkaServer)
[2018-06-19 13:13:06,171] FATAL Fatal error during KafkaServerStartable startup. Prepare to shutdown (kafka.server.KafkaServerStartable)
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 6000
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1232)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:156)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:130)
	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:76)
	at kafka.utils.ZkUtils$.apply(ZkUtils.scala:58)
	at kafka.server.KafkaServer.initZk(KafkaServer.scala:327)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:200)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:39)
	at kafka.Kafka$.main(Kafka.scala:67)
	at kafka.Kafka.main(Kafka.scala)
[2018-06-19 13:13:06,172] INFO shutting down (kafka.server.KafkaServer)
```

**Comment by sscaling** [comment]
Closing as OP seems to have solved issue by increasing zookeeper timeout

**Comment by jesusmariajurado** [comment]
I was using microk8s with this warning

WARNING:  IPtables FORWARD policy is DROP. Consider enabling traffic forwarding with: sudo iptables -P FORWARD ACCEPT

fixing it worked for me
