### ISSUE TITLE
Issue starting kafka: java.lang.NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by josselin-c** [wurstmeister/kafka-docker#26]
When trying to set my kafka cluster up, zookeeper starts but kafka doesn't (I tried w/ branch master and 0.8.2). 
Here are the logs of the kafka container:

```
[joss@joss]$ docker logs 3294fb2e90a5
2015/01/29 14:56:53 Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
[2015-01-29 14:56:54,296] FATAL  (kafka.Kafka$)
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:493)
	at java.lang.Integer.parseInt(Integer.java:514)
	at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:231)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:31)
	at kafka.utils.VerifiableProperties.getIntInRange(VerifiableProperties.scala:75)
	at kafka.utils.VerifiableProperties.getIntInRange(VerifiableProperties.scala:48)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:75)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:31)
	at kafka.Kafka$.main(Kafka.scala:35)
	at kafka.Kafka.main(Kafka.scala)
```

Here is my fig.yml:
```
[joss@joss]$ cat fig.yml 
zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181"
kafka:
  image: wurstmeister/kafka:0.8.2-beta
  ports:
    - "9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 10.42.2.217
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by rthille** [comment]
It looks to me like the 'start-kafka.sh' script is running docker in the container to find the port on the docker running host that's forwarded into port 9092 in the container.  That's failing for some reason.

If you 'docker exec -it  <container-id> /bin/bash' to get into the running container, can you run 'docker ps' or 'docker port `hostname` 9092' ?

**Comment by josselin-c** [comment]
Turns out docker/fig wasn't mounting /var/run/docker.sock in the container. Upgrading fig & docker and running "fig rm" solved the issue.

**Comment by luck02** [comment]
@josselin-c  what versions are you now running / were running?  See my issue (https://github.com/wurstmeister/kafka-docker/issues/30) 

I'm running 
```
➜  kafka-docker git:(master) ✗ fig --version
fig 1.0.1
➜  kafka-docker git:(master) ✗ docker --version
Docker version 1.4.1, build 5bc2ff8/1.4.1
➜  kafka-docker git:(master) ✗ 
```

and experiencing something similar.

**Comment by luck02** [comment]
One more piece of the puzzle:
```
root@ebbeed405ae2:/var/run# ls -alh
ls: cannot access docker.sock: Permission denied
total 32K
drwxr-xr-x.  7 root root   4.0K Feb 10 03:34 .
drwxr-xr-x. 22 root root   4.0K Feb 10 03:34 ..
-??????????  ? ?    ?         ?            ? docker.sock
drwxrwxrwt.  2 root root   4.0K Jan 28 16:28 lock
-rw-r--r--.  1 root root    109 Jan 28 16:28 motd.dynamic
drwxr-xr-x.  2 root netdev 4.0K Jan 28 16:28 network
drwxr-xr-x.  3 root root   4.0K Jan 28 16:28 resolvconf
drwxr-xr-x.  2 root root   4.0K Jan 28 16:28 sendsigs.omit.d
drwxr-xr-x.  2 root root   4.0K Jan 28 16:28 shm
-rw-rw-r--.  1 root utmp      0 Jan 28 16:28 utmp
```

**Comment by josselin-c** [comment]
I have the same versions as you do: docker 1.4.1 & fig 1.0.1.

**Comment by luck02** [comment]
I carried on commenting on issue https://github.com/wurstmeister/kafka-docker/issues/30

I got past that problem by setting selinux to permissive, but then ran into network issues further on.
