### ISSUE TITLE
Latest version couldn't connect with brokers when started via docker-compose

### ISSUE THREAD

**Issue by mangatmodi** [wurstmeister/kafka-docker#302]
I have following snippet in docker-compose.yml

```
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      skynet:
        aliases:
          - zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    networks:
      skynet:
        aliases:
          - kafka
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      KAFKA_CREATE_TOPICS: "dev-test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_NAME}
```

Here I am using hostname from host machine to advertiser kafka broker's hostname. Until now Kafka was able to connect with brokers and everything was running smoothly. However sometime after the release of 1.0.1, I am getting LEADER_NOT_AVAILABLE error.

I have tried following analysis:-

1. Kafka and Zookeeper containers are able to connect with each other with  network aliases (telnet)
2. At host machine, telnet is again able to connect with both the services with both hostname and localhost.
3. however using bin/kafka-console-consumer to read fails with LEADER_NOT_AVAILABLE error, that means that consumers are not able to get any leader from zookeper.
4. Inside kafka container we have log lines ->

`ERROR [KafkaApi-1001] Number of alive brokers '0' does not meet the required replication factor '1' for the offsets topic (configured via 'offsets.topic.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet. (kafka.server.KafkaApis)`

5. Inside zookeper shell, I can see correct values for the following nodes:-

```
/brokers/topics
/config/topics
/brokers/ids
```

Note that using `wurstmeister/kafka:1.0.0` image solved the issue. Am I using a configuration which is no longer supported by the image?

Thanks,

**Comment by sscaling** [comment]
@mangatmodi - Please could you attach the broker config (output in the kafka startup logs). Also what docker version / os are you running this on?

**Comment by mikestov** [comment]
I'm having the same issue when upgrading from version 1.0.0 to 1.1. I'm using docker "Docker version 18.03.0-ce, build 0520e24" and CentOS 7. When I reverted back to kafka 1.0.0, it started working again. Here's my log (IPs scrubbed):

`kafka_1                    | [2018-04-05 19:53:51,878] INFO KafkaConfig values:
kafka_1                    | 	advertised.host.name = XXX.XXX.XXX.XXX
kafka_1                    | 	advertised.listeners = XXX.XXX.XXX.XXX
kafka_1                    | 	advertised.port = 9092
kafka_1                    | 	alter.config.policy.class.name = null
kafka_1                    | 	authorizer.class.name =
kafka_1                    | 	auto.create.topics.enable = true
kafka_1                    | 	auto.leader.rebalance.enable = true
kafka_1                    | 	background.threads = 10
kafka_1                    | 	broker.id = -1
kafka_1                    | 	broker.id.generation.enable = true
kafka_1                    | 	broker.rack = null
kafka_1                    | 	compression.type = producer
kafka_1                    | 	connections.max.idle.ms = 600000
kafka_1                    | 	controlled.shutdown.enable = true
kafka_1                    | 	controlled.shutdown.max.retries = 3
kafka_1                    | 	controlled.shutdown.retry.backoff.ms = 5000
kafka_1                    | 	controller.socket.timeout.ms = 30000
kafka_1                    | 	create.topic.policy.class.name = null
kafka_1                    | 	default.replication.factor = 1
kafka_1                    | 	delete.records.purgatory.purge.interval.requests = 1
kafka_1                    | 	delete.topic.enable = true
kafka_1                    | 	fetch.purgatory.purge.interval.requests = 1000
kafka_1                    | 	group.initial.rebalance.delay.ms = 0
kafka_1                    | 	group.max.session.timeout.ms = 300000
kafka_1                    | 	group.min.session.timeout.ms = 6000
kafka_1                    | 	host.name =
kafka_1                    | 	inter.broker.listener.name = null
kafka_1                    | 	inter.broker.protocol.version = 1.0-IV0
kafka_1                    | 	leader.imbalance.check.interval.seconds = 300
kafka_1                    | 	leader.imbalance.per.broker.percentage = 10
kafka_1                    | 	listener.security.protocol.map = PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
kafka_1                    | 	listeners = null
kafka_1                    | 	log.cleaner.backoff.ms = 15000
kafka_1                    | 	log.cleaner.dedupe.buffer.size = 134217728
kafka_1                    | 	log.cleaner.delete.retention.ms = 86400000
kafka_1                    | 	log.cleaner.enable = true
kafka_1                    | 	log.cleaner.io.buffer.load.factor = 0.9
kafka_1                    | 	log.cleaner.io.buffer.size = 524288
kafka_1                    | 	log.cleaner.io.max.bytes.per.second = 1.7976931348623157E308
kafka_1                    | 	log.cleaner.min.cleanable.ratio = 0.5
kafka_1                    | 	log.cleaner.min.compaction.lag.ms = 0
kafka_1                    | 	log.cleaner.threads = 1
kafka_1                    | 	log.cleanup.policy = [delete]
kafka_1                    | 	log.dir = /tmp/kafka-logs
kafka_1                    | 	log.dirs = /kafka/kafka-logs-73aba801c22d
kafka_1                    | 	log.flush.interval.messages = 9223372036854775807
kafka_1                    | 	log.flush.interval.ms = null
kafka_1                    | 	log.flush.offset.checkpoint.interval.ms = 60000
kafka_1                    | 	log.flush.scheduler.interval.ms = 9223372036854775807
kafka_1                    | 	log.flush.start.offset.checkpoint.interval.ms = 60000
kafka_1                    | 	log.index.interval.bytes = 4096
kafka_1                    | 	log.index.size.max.bytes = 10485760
kafka_1                    | 	log.message.format.version = 1.0-IV0
kafka_1                    | 	log.message.timestamp.difference.max.ms = 9223372036854775807
kafka_1                    | 	log.message.timestamp.type = CreateTime
kafka_1                    | 	log.preallocate = false
kafka_1                    | 	log.retention.bytes = -1
kafka_1                    | 	log.retention.check.interval.ms = 300000
kafka_1                    | 	log.retention.hours = 168
kafka_1                    | 	log.retention.minutes = null
kafka_1                    | 	log.retention.ms = null
kafka_1                    | 	log.roll.hours = 168
kafka_1                    | 	log.roll.jitter.hours = 0
kafka_1                    | 	log.roll.jitter.ms = null
kafka_1                    | 	log.roll.ms = null
kafka_1                    | 	log.segment.bytes = 1073741824
kafka_1                    | 	log.segment.delete.delay.ms = 60000
kafka_1                    | 	max.connections.per.ip = 2147483647
kafka_1                    | 	max.connections.per.ip.overrides =
kafka_1                    | 	message.max.bytes = 1000012
kafka_1                    | 	metric.reporters = []
kafka_1                    | 	metrics.num.samples = 2
kafka_1                    | 	metrics.recording.level = INFO
kafka_1                    | 	metrics.sample.window.ms = 30000
kafka_1                    | 	min.insync.replicas = 1
kafka_1                    | 	num.io.threads = 8
kafka_1                    | 	num.network.threads = 3
kafka_1                    | 	num.partitions = 1
kafka_1                    | 	num.recovery.threads.per.data.dir = 1
kafka_1                    | 	num.replica.fetchers = 1
kafka_1                    | 	offset.metadata.max.bytes = 4096
kafka_1                    | 	offsets.commit.required.acks = -1
kafka_1                    | 	offsets.commit.timeout.ms = 5000
kafka_1                    | 	offsets.load.buffer.size = 5242880
kafka_1                    | 	offsets.retention.check.interval.ms = 600000
kafka_1                    | 	offsets.retention.minutes = 1440
kafka_1                    | 	offsets.topic.compression.codec = 0
kafka_1                    | 	offsets.topic.num.partitions = 50
kafka_1                    | 	offsets.topic.replication.factor = 1
kafka_1                    | 	offsets.topic.segment.bytes = 104857600
kafka_1                    | 	port = 9092
kafka_1                    | 	principal.builder.class = null
kafka_1                    | 	producer.purgatory.purge.interval.requests = 1000
kafka_1                    | 	queued.max.request.bytes = -1
kafka_1                    | 	queued.max.requests = 500
kafka_1                    | 	quota.consumer.default = 9223372036854775807
kafka_1                    | 	quota.producer.default = 9223372036854775807
kafka_1                    | 	quota.window.num = 11
kafka_1                    | 	quota.window.size.seconds = 1
kafka_1                    | 	replica.fetch.backoff.ms = 1000
kafka_1                    | 	replica.fetch.max.bytes = 1048576
kafka_1                    | 	replica.fetch.min.bytes = 1
kafka_1                    | 	replica.fetch.response.max.bytes = 10485760
kafka_1                    | 	replica.fetch.wait.max.ms = 500
kafka_1                    | 	replica.high.watermark.checkpoint.interval.ms = 5000
kafka_1                    | 	replica.lag.time.max.ms = 10000
kafka_1                    | 	replica.socket.receive.buffer.bytes = 65536
kafka_1                    | 	replica.socket.timeout.ms = 30000
kafka_1                    | 	replication.quota.window.num = 11
kafka_1                    | 	replication.quota.window.size.seconds = 1
kafka_1                    | 	request.timeout.ms = 30000
kafka_1                    | 	reserved.broker.max.id = 1000
kafka_1                    | 	sasl.enabled.mechanisms = [GSSAPI]
kafka_1                    | 	sasl.kerberos.kinit.cmd = /usr/bin/kinit
kafka_1                    | 	sasl.kerberos.min.time.before.relogin = 60000
kafka_1                    | 	sasl.kerberos.principal.to.local.rules = [DEFAULT]
kafka_1                    | 	sasl.kerberos.service.name = null
kafka_1                    | 	sasl.kerberos.ticket.renew.jitter = 0.05
kafka_1                    | 	sasl.kerberos.ticket.renew.window.factor = 0.8
kafka_1                    | 	sasl.mechanism.inter.broker.protocol = GSSAPI
kafka_1                    | 	security.inter.broker.protocol = PLAINTEXT
kafka_1                    | 	socket.receive.buffer.bytes = 102400
kafka_1                    | 	socket.request.max.bytes = 104857600
kafka_1                    | 	socket.send.buffer.bytes = 102400
kafka_1                    | 	ssl.cipher.suites = null
kafka_1                    | 	ssl.client.auth = none
kafka_1                    | 	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
kafka_1                    | 	ssl.endpoint.identification.algorithm = null
kafka_1                    | 	ssl.key.password = null
kafka_1                    | 	ssl.keymanager.algorithm = SunX509
kafka_1                    | 	ssl.keystore.location = null
kafka_1                    | 	ssl.keystore.password = null
kafka_1                    | 	ssl.keystore.type = JKS
kafka_1                    | 	ssl.protocol = TLS
kafka_1                    | 	ssl.provider = null
kafka_1                    | 	ssl.secure.random.implementation = null
kafka_1                    | 	ssl.trustmanager.algorithm = PKIX
kafka_1                    | 	ssl.truststore.location = null
kafka_1                    | 	ssl.truststore.password = null
kafka_1                    | 	ssl.truststore.type = JKS
kafka_1                    | 	transaction.abort.timed.out.transaction.cleanup.interval.ms = 60000
kafka_1                    | 	transaction.max.timeout.ms = 900000
kafka_1                    | 	transaction.remove.expired.transaction.cleanup.interval.ms = 3600000
kafka_1                    | 	transaction.state.log.load.buffer.size = 5242880
kafka_1                    | 	transaction.state.log.min.isr = 1
kafka_1                    | 	transaction.state.log.num.partitions = 50
kafka_1                    | 	transaction.state.log.replication.factor = 1
kafka_1                    | 	transaction.state.log.segment.bytes = 104857600
kafka_1                    | 	transactional.id.expiration.ms = 604800000
kafka_1                    | 	unclean.leader.election.enable = false
kafka_1                    | 	zookeeper.connect = zookeeper:2181
kafka_1                    | 	zookeeper.connection.timeout.ms = 6000
kafka_1                    | 	zookeeper.session.timeout.ms = 6000
kafka_1                    | 	zookeeper.set.acl = false
kafka_1                    | 	zookeeper.sync.time.ms = 2000
kafka_1                    |  (kafka.server.KafkaConfig)
kafka_1                    | [2018-04-05 19:53:51,932] FATAL  (kafka.Kafka$)
kafka_1                    | java.lang.IllegalArgumentException: Error creating broker listeners from 'XXX.XXX.XXX.XXX': Unable to parse XXX.XXX.XXX.XXX to a broker endpoint
kafka_1                    | 	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:278)
kafka_1                    | 	at kafka.server.KafkaConfig.getAdvertisedListeners(KafkaConfig.scala:1130)
kafka_1                    | 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1090)
kafka_1                    | 	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:881)
kafka_1                    | 	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:878)
kafka_1                    | 	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
kafka_1                    | 	at kafka.Kafka$.main(Kafka.scala:82)
kafka_1                    | 	at kafka.Kafka.main(Kafka.scala)
kafka_1                    | Caused by: kafka.common.KafkaException: Unable to parse XXX.XXX.XXX.XXX to a broker endpoint
kafka_1                    | 	at kafka.cluster.EndPoint$.createEndPoint(EndPoint.scala:57)
kafka_1                    | 	at kafka.utils.CoreUtils$.$anonfun$listenerListToEndPoints$6(CoreUtils.scala:275)
kafka_1                    | 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
kafka_1                    | 	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
kafka_1                    | 	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
kafka_1                    | 	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
kafka_1                    | 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
kafka_1                    | 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
kafka_1                    | 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
kafka_1                    | 	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:275)
kafka_1                    | 	... 7 more
`

**Comment by sscaling** [comment]
@mangatmodi - I used the following docker compose no problem with the latest image.

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "dev-test:1:1"
      KAFKA_ADVERTISED_HOST_NAME: 192.168.128.162
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

where `192.168.128.162` is my machines IP on my local network.

**Comment by mangatmodi** [comment]
Sorry for late reply. I couldn't come online. I was trying Hostname not IP.  It was working on my local machine which was MacOs Sierra - `10.12., docker - 17.12.0-ce, docker-compose 1.20.1`, However failing on circle-ci machine executor - `circleci/classic:201711-01 – docker 17.11.0-ce, docker-compose 1.17.1`

[kafka.log](https://github.com/wurstmeister/kafka-docker/files/1883281/kafka.log)

**Comment by sscaling** [comment]
@mangatmodi Looking at what I think are the relevant parts of the log

```
kafka_1                | 	advertised.host.name = default-2d484b78-5365-4e5f-891e-488db4fe1ed2
kafka_1                | 	advertised.listeners = null
kafka_1                | 	advertised.port = null
```
You haven't configured an advertised port. For this to be automatic, you either need to specify `KAFKA_ADVERTISED_PORT` if this is known up front (which looks like you want this to be `9092` or mount the `docker.sock` unix socket through so this can be determined programatically.

**Comment by mangatmodi** [comment]
Ouch, I thought `KAFKA_ADVERTISED_PORT` is optional if 9092 is used. If not optional, then it was working well in past versions.

**Comment by mangatmodi** [comment]
Thanks @sscaling !
