### ISSUE TITLE
Cannot connect to zookeeper after restarting zookeeper pod

### ISSUE THREAD

**Issue by junaidrazzaq323** [wurstmeister/kafka-docker#378]
I am running Kafka and Zookeeper on a Kubernetes setup. I launch both kafka and zookeeper pod. They are both working fine. I bring down zookeeper pod and kafka has the following logs:

```
java.net.NoRouteToHostException: Host is unreachable
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2018-08-02 15:29:10,380] INFO Opening socket connection to server zookeeper.casb-deployment.svc.cluster.local/10.103.187.203:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-02 15:29:16,384] WARN Client session timed out, have not heard from server in 7184ms for sessionid 0x164fb39384c0000 (org.apache.zookeeper.ClientCnxn)
[2018-08-02 15:29:16,385] INFO Client session timed out, have not heard from server in 7184ms for sessionid 0x164fb39384c0000, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2018-08-02 15:29:18,230] INFO Opening socket connection to server zookeeper.casb-deployment.svc.cluster.local/10.103.187.203:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-02 15:29:24,230] WARN Client session timed out, have not heard from server in 7745ms for sessionid 0x164fb39384c0000 (org.apache.zookeeper.ClientCnxn)
[2018-08-02 15:29:24,231] INFO Client session timed out, have not heard from server in 7745ms for sessionid 0x164fb39384c0000, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2018-08-02 15:29:25,681] INFO Opening socket connection to server zookeeper.casb-deployment.svc.cluster.local/10.103.187.203:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-08-02 15:29:31,689] WARN Client session timed out, have not heard from server in 7358ms for sessionid 0x164fb39384c0000 (org.apache.zookeeper.ClientCnxn)
[2018-08-02 15:29:31,689] INFO Client session timed out, have not heard from server in 7358ms for sessionid 0x164fb39384c0000, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2018-08-02 15:29:33,488] INFO Opening socket connection to server zookeeper.casb-deployment.svc.cluster.local/10.103.187.203:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
```

Even after restarting zookeeper, Kafka cannot connect to the zookeeper pod and keeps on throwing the same exceptions.

**Kafka.yaml:**

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: casb-deployment
  name: kafkaservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafkaservice
    spec:
      hostname: kafkaservice
      containers:
      - name: kafkaservice
        imagePullPolicy: IfNotPresent
        image: wurstmeister/kafka:1.1.0
        env:
         - name: KAFKA_BROKER_ID
           value: "1"
         - name: KAFKA_ADVERTISED_HOST_NAME
           value: "kafkaservice"
         - name: KAFKA_CREATE_TOPICS
           value: "topic1:1:1"
         - name: KAFKA_MESSAGE_TIMESTAMP_TYPE
           value: "LogAppendTime"
         - name: KAFKA_LOG_MESSAGE_TIMESTAMP_TYPE
           value: "LogAppendTime"   
         - name: KAFKA_ZOOKEEPER_CONNECT
           value: "zookeeper:2181"
        ports: 
        - name: port9092
          containerPort: 9092          
        volumeMounts:
        - mountPath: /kafka/kafka-logs-kafkaservice
          name: kafka-volume
      volumes:
      - name: kafka-volume
        hostPath:
          path: /var/lib/kafka-logs

apiVersion: v1
kind: Service
metadata:
  namespace: casb-deployment
  name: kafkaservice
  labels:
    app: kafkaservice
spec:
  selector:
    app: kafkaservice
  ports:
  - name: port9092
    port: 9092
    targetPort: 9092
    protocol: TCP

```

**Zookeeper.yaml:**

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: casb-deployment
  name: zookeeper
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      hostname: zookeeper
      containers:
      - name: zookeeper
        imagePullPolicy: IfNotPresent
        image: zookeeper:3.3.6
        env:
         - name: ZOO_MY_ID
           value: "1"
        ports: 
        - name: port2181
          containerPort: 2181
        volumeMounts:
        - mountPath: /data
          name: zookeeper-data
        - mountPath: /datalogs
          name: zookeeper-logs
      volumes:
      - name: zookeeper-data
        hostPath:
          path: /var/lib/zookeeper/data
      - name: zookeeper-logs
        hostPath:
          path: /var/lib/zookeeper/logs

apiVersion: v1
kind: Service
metadata:
  namespace: casb-deployment
  name: zookeeper
  labels:
    app: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
  - name: port2181
    port: 2181
    targetPort: 2181
    protocol: TCP
```

I am guessing its a Kubernetes related issue. I also looked into [this issue](https://github.com/wurstmeister/kafka-docker/issues/47) but I am not sure if its related to mine.

**Comment by sscaling** [comment]
Looking at the logs, I'd guess it was something like state being maintained in the zookeeper client (similar to https://github.com/wurstmeister/kafka-docker/issues/374). 

A few basic things to check:
* zookeeper is configured correctly (https://hub.docker.com/_/zookeeper/ would indicate you'd need to specify the `ZOO_SERVERS` environment var or disable replicated mode)
* zookeeper is healthy after restart
* restarting kafka recovers from this situation

It may also be known behaviour, normally zookeeper would be run as a quorum in replicated mode so that the cluster can tolerate failure / restarts. Only having one zookeeper node is very fragile.

However, it seems as though this issue is either Kafka / Zookeeper / Kubernetes related - not to do with the kafka-docker image itself. I'd recommend trying to ask on the respective mailing lists / forums for more specific help. 

I don't have any free bandwidth at the moment to dig into this so I'll leave the issue open for a while to see if anyone else can provide help / assistance.

Thanks

**Comment by sscaling** [comment]
No further response from OP / community so closing due to staleness.

**Comment by rishabh96b** [comment]
Hey @junaidrazzaq323 , were you able to troubleshoot this issue? I am also getting the similar error.

**Comment by sekhrivijay** [comment]
I have similar issue with zookeeper and solr.  Pod restart of zk causes solr to have this error.
Restarting of solr node fixes the issue. 
```
java.net.NoRouteToHostException: Host is unreachable
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)

```
Is there any fix for this issue ? The ZK client used by solr most likely has this bug. The solr version is 
solr:7.2.1
