### ISSUE TITLE
zookeeper client time while trying to create topics

### ISSUE THREAD

**Issue by confusedIamHowBoutU** [wurstmeister/kafka-docker#384]
Following that tutorial:
http://wurstmeister.github.io/kafka-docker/

start-kafka-shell.sh 10.123.186.156 10.123.186.156:2181
$KAFKA_HOME/bin/kafka-topics.sh --create --topic topic \
--partitions 4 --zookeeper $ZK --replication-factor 2
Keeping time out now sure what is going to wrong. I have tried few different configuration of the start shell command plus I am running on windows.

Is there some glaring missing?

```
Exception in thread "main" kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
        at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply$mcV$sp(ZooKeeperClient.scala:230)
        at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply(ZooKeeperClient.scala:226)
        at kafka.zookeeper.ZooKeeperClient$$anonfun$kafka$zookeeper$ZooKeeperClient$$waitUntilConnected$1.apply(ZooKeeperClient.scala:226)
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:251)
        at kafka.zookeeper.ZooKeeperClient.kafka$zookeeper$ZooKeeperClient$$waitUntilConnected(ZooKeeperClient.scala:226)
        at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:95)
        at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1580)
        at kafka.admin.TopicCommand$.main(TopicCommand.scala:57)
        at kafka.admin.TopicCommand.main(TopicCommand.scala)
```

```
# file name: docker-compose

version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.123.186.156
      KAFKA_ZOOKEEPER_CONNECT: 10.123.186.156:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by sscaling** [comment]
I'm not familiar with how Windows handles it networking. It looks like there is some special networking to run within the VM (https://docs.docker.com/docker-for-windows/networking/) so perhaps your public address isn't resolvable to the docker daemon (however, it does suggest with the `-p 8080:80` mapping you can access service on `localhost:8080`). This document contradicts that: https://docs.docker.com/docker-for-windows/troubleshoot/#limitations-of-windows-containers-for-localhost-and-published-ports but does indicate that you can use the public NIC address (which I'm assuming is the `10.123.186.156` above?)

As per the [connectivity guide](https://github.com/wurstmeister/kafka-docker/wiki/Connectivity) make sure you can route to the address specified in `KAFKA_ADVERTISED_HOST_NAME` from the client (e.g. `apk update && apk add busybox-extras && telnet 10.123.186.156 9092`)

**Comment by cfuentesgithub** [comment]
@confusedIamHowBoutU hello, i have the same problem, did you find the solution?, in my case i'm trying to run it in a VirtualBox (Centos 7) and also in Mac system.

Any help will be aprappreciated
