### ISSUE TITLE
NoBrokersAvailable problem

### ISSUE THREAD

**Issue by chunzhenzyd** [wurstmeister/kafka-docker#400]
I run zookeeper and kafka container with:
docker run -d --restart=always --name ims_zookeeper --network ims_network wurstmeister/zookeeper

docker run -d --restart=always --name ims_kafka --network ims_network \
           -e KAFKA_ADVERTISED_HOST_NAME=localhost -e KAFKA_ZOOKEEPER_CONNECT=ims_zookeeper:2181 \
           -e KAFKA_CREATE_TOPICS=imslog:1:1 -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
           wurstmeister/kafka

then run a python container ims_python with same network ims_network,
but I can't connect from ims_python to ims_kafka with:
PRODUCER = KafkaProducer(bootstrap_servers=["ims_kafka:9092"])
Error:
kafka.errors.NoBrokersAvailable: NoBrokersAvailable

Please help !

**Comment by chunzhenzyd** [comment]
Hi,

I change kafka run command to:
docker run -d --restart=always --name ims_kafka --network ims_network \
           -e KAFKA_ZOOKEEPER_CONNECT=ims_zookeeper:2181 \
           -e KAFKA_ADVERTISED_HOST_NAME=192.168.18.153 -e KAFKA_ADVERTISED_PORT=9092 \
           -e KAFKA_CREATE_TOPICS=imslog:1:1 -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
           wurstmeister/kafka

then it works.. But I still don't understand. Because I didn't export the kafka port? And KAFKA_ADVERTISED_HOST_NAME should be set to the real outer host ip?

**Comment by chunzhenzyd** [comment]
Hi,

I set KAFKA_ADVERTISED_HOST_NAME=ims_network, it still works.
I set KAFKA_ADVERTISED_HOST_NAME=localhost, it not works.

**Comment by sscaling** [comment]
python container will resolve localhost to it's IP, not that of the Kafka broker. That's why you need to have a routable address as the advertised hostname. Have you read the [Connectivity Guide](https://github.com/wurstmeister/kafka-docker/wiki/Connectivity)

**Comment by iamsais** [comment]
I guess we should use KAFKA_PORT instead of KAFKA_ADVERTISED_PORT.

```
docker run -d --restart=always --name ims_kafka --network ims_network 
 -e KAFKA_ZOOKEEPER_CONNECT=ims_zookeeper:2181 
 -e KAFKA_PORT=9092 
 -e KAFKA_CREATE_TOPICS=imslog:1:1 
 -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 
wurstmeister/kafka
```

If you use KAFKA_ADVERTISED_PORT, then KAFKA_ADVERTISED_HOST_NAME should be your HOST_IP.

**Comment by sscaling** [comment]
> I guess we should use KAFKA_PORT instead of KAFKA_ADVERTISED_PORT.

They are two distinct configurations  (See [Kafka docs](http://kafka.apache.org/documentation/#brokerconfigs))

* `port` - "the port to listen and accept connections on"
* `advertised.port` - "The port to publish to ZooKeeper for clients to use. In IaaS environments, this may need to be different from the port to which the broker binds. If this is not set, it will publish the same port that the broker binds to."

> If you use KAFKA_ADVERTISED_PORT, then KAFKA_ADVERTISED_HOST_NAME should be your HOST_IP.

Not necessarily - hostname is what clients will connect to - the brokers may have a VIP / load-balancer / proxy / some other network name (resolvable via DNS to clients).

**Comment by chunzhenzyd** [comment]
Hi,
first created network ims_network:
docker network create ims_network

I run kafka container with:
docker run -d --restart=always --name ims_zookeeper --network ims_network \
           -v /etc/localtime:/etc/localtime:ro \
           wurstmeister/zookeeper
docker run -d --restart=always --name ims_kafka --network ims_network \
           -e KAFKA_ZOOKEEPER_CONNECT=ims_zookeeper:2181 \
           -e KAFKA_ADVERTISED_HOST_NAME=ims_network -e KAFKA_ADVERTISED_PORT=9092 \
           -e KAFKA_CREATE_TOPICS=imslog:1:1 -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
           -v /etc/localtime:/etc/localtime:ro \
           wurstmeister/kafka

but I met error below when I try to send msgs from other container(python env container):

kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs

the code in python env container:

from kafka import KafkaProducer
from kafka.errors import KafkaError

PRODUCER = KafkaProducer(bootstrap_servers=["172.18.0.7:9092"])

if __name__ == '__main__':
    payload = '{"termIP":"192.168.17.47","material_id":"1533","project":"default","termID":"70:F8:E7:90:02:D7","material_name":"1.jpg","date":"2018\/09\/26 09:40:00","event":"play"}'
    PRODUCER.send('imslog', payload)

the full error:
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    PRODUCER.send('imslog', payload)
  File "/usr/lib/python2.6/site-packages/kafka/producer/kafka.py", line 481, in send
    self._wait_on_metadata(topic, self.config['max_block_ms'] / 1000.0)
  File "/usr/lib/python2.6/site-packages/kafka/producer/kafka.py", line 598, in _wait_on_metadata
    "Failed to update metadata after %s secs.", max_wait)
kafka.errors.KafkaTimeoutError: KafkaTimeoutError: ('Failed to update metadata after %s secs.', 60.0)

Please help!

**Comment by sscaling** [comment]
1. You say that you create the 'ims_network' first, but have not provided how this is done
2. You have not provided how the python container is started
3. the `bootstrap_servers` should really match the interface specified in `KAFKA_ADVERTISED_HOSTS`. It is unclear if this is the case from the information provided 
4. I'd recommend using docker-compose for configuring this (to remove the need for manually creating networks - and make reproduction of issue much easier)
5. Please verify connectivity with the simple console consumer/producer or kafkacat (known compatible tools). If that is the case, then it seems you have an issue with your Python code and/or libraries

**Comment by chunzhenzyd** [comment]
Hi sscaling:

1. I create ims_network with: 
docker network create ims_network

2. I create python container with:
docker run -d --restart=always --name ims_uwsgi --network ims_network \
           --ulimit nofile=4096:4096 --ulimit nproc=4096:4096 --sysctl net.core.somaxconn=4096 \
           -v /home/clear/ims/conf/cron/crontabfile:/etc/cron.d/crontabfile \
           -v /home/clear/ims/conf/uwsgi:/etc/uwsgi.d -v /var/log/uwsgi:/var/log/uwsgi \
           -v /usr/local/clearcrane/ims:/usr/local/clearcrane/ims \
           -v /home/clearims/resource:/home/clearims/resource \
           -v /etc/localtime:/etc/localtime:ro \
           ims_uwsgi
(ims_uwsgi is a centos6.9 base container)

3. I set bootstrap_servers with:
PRODUCER = KafkaProducer(bootstrap_servers=["172.18.0.7:9092"])  (not work)
PRODUCER = KafkaProducer(bootstrap_servers=["ims_kafka:9092"])  (not work)
(172.18.0.7 is the ims_kafka container ip)

4. I think it's the simplest scenario, and I haven't learn how to use docker-compose yet.

5. It's not python code problem ( and I think it's not libraries problem, I tried kafka-python==1.3.1 and kafka-python==1.3.5, both not work ), the code is ok, because it works without docker( in centos 6.9, install kafka directory)

BR

**Comment by chunzhenzyd** [comment]
Hi sscaling:

Some people met the same problem:
https://github.com/dpkp/kafka-python/issues/607

https://stackoverflow.com/questions/48261501/kafka-errors-kafkatimeouterror-kafkatimeouterror-failed-to-update-metadata-aft

But I still don't find the solution...

BR

**Comment by chunzhenzyd** [comment]
Hi,

I change kafka container run command to:

docker run -d --name ims_kafka --network ims_network \
           -e KAFKA_ZOOKEEPER_CONNECT=ims_zookeeper:2181 \
           -e KAFKA_LISTENERS=PLAINTEXT://:9092 -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://ims_kafka:9092 \
           -e KAFKA_CREATE_TOPICS=imslog:1:1 -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
           -v /etc/localtime:/etc/localtime:ro \
           wurstmeister/kafka

then I run the python code, and there is no timeout problem, but kafka consumer can't receive the msgs, where they were sent ???

1. go in kafka container:
docker exec -it ims_kafka /bin/bash
2. run kafka consumer:
/opt/kafka/bin/kafka-console-consumer.sh -bootstrap-server ims_zookeeper:2181 --from-beginning --topic imslog
(no msgs received always)

bash-4.4# /opt/kafka/bin/kafka-topics.sh --zookeeper ims_zookeeper:2181 --list
__consumer_offsets
imslog

**Comment by chunzhenzyd** [comment]
Hi sscaling,

I restart zookeeper, and it works...
Thanks very much for your patience!

My commands:

echo "IMS > run zookeeper docker..."
docker run -d --restart=always --name ims_zookeeper --network ims_network \
           -v /etc/localtime:/etc/localtime:ro \
           wurstmeister/zookeeper
sleep 10
echo "IMS > run kafka docker..."
docker run -d --restart=always --name ims_kafka --network ims_network \
           -e KAFKA_ZOOKEEPER_CONNECT=ims_zookeeper:2181 \
           -e KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092 -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://ims_kafka:9092 \
           -e KAFKA_CREATE_TOPICS=imslog:1:1 -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
           -v /etc/localtime:/etc/localtime:ro \
           wurstmeister/kafka
