### ISSUE TITLE
cannot create topics and partitions when using  jmx_prometheus_javaagent in KAFKA_OPTS, 

### ISSUE THREAD

**Issue by akdj** [wurstmeister/kafka-docker#433]
I want to create some topics:  mybox_device_event, mytopic_box_status_event, mytopic_box_reply_event

and i want to monitor with Prometheus jmx javaagent.  however after i added the java agent as KAFKA_OPTS, the kafka docker container cannot create topics and theirs partitions.

I don't know I should ask to who? If you have an idea, can you help me? 

```

[2018-11-29 14:57:15,202] INFO [GroupMetadataManager brokerId=1001] Finished loading offsets and group metadata from __consumer_offsets-42 in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)


[2018-11-29 14:57:15,202] INFO [GroupMetadataManager brokerId=1001] Finished loading offsets and group metadata from __consumer_offsets-45 in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)


[2018-11-29 14:57:15,202] INFO [GroupMetadataManager brokerId=1001] Finished loading offsets and group metadata from __consumer_offsets-48 in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)


creating topics: mybox_device_event:5:1


creating topics: mytopic_box_status_event:5:1


creating topics:  mytopic_box_reply_event:5:1



Exception in thread "main" java.lang.reflect.InvocationTargetException


	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)


	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)


	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


	at java.lang.reflect.Method.invoke(Method.java:498)


	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)


	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)


Caused by: java.net.BindException: Address in use


	at sun.nio.ch.Net.bind0(Native Method)


	at sun.nio.ch.Net.bind(Net.java:433)


	at sun.nio.ch.Net.bind(Net.java:425)


	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)


	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)


	at sun.net.httpserver.ServerImpl.bind(ServerImpl.java:133)


	at sun.net.httpserver.HttpServerImpl.bind(HttpServerImpl.java:54)


	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer.<init>(HTTPServer.java:145)


	at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:49)


	... 6 more


FATAL ERROR in native method: processing of -javaagent failed


Exception in thread "main" java.lang.reflect.InvocationTargetException


	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)


	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)


	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


	at java.lang.reflect.Method.invoke(Method.java:498)


	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)


	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)


Caused by: java.net.BindException: Address in use


	at sun.nio.ch.Net.bind0(Native Method)


	at sun.nio.ch.Net.bind(Net.java:433)


	at sun.nio.ch.Net.bind(Net.java:425)


	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)


	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)


	at sun.net.httpserver.ServerImpl.bind(ServerImpl.java:133)


	at sun.net.httpserver.HttpServerImpl.bind(HttpServerImpl.java:54)


FATAL ERROR in native method: processing of -javaagent failed


	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer.<init>(HTTPServer.java:145)


	at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:49)


	... 6 more


Exception in thread "main" java.lang.reflect.InvocationTargetException


	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)


	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)


	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


	at java.lang.reflect.Method.invoke(Method.java:498)


	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)


	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)


Caused by: java.net.BindException: Address in use


	at sun.nio.ch.Net.bind0(Native Method)


	at sun.nio.ch.Net.bind(Net.java:433)


	at sun.nio.ch.Net.bind(Net.java:425)


	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)


	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)


	at sun.net.httpserver.ServerImpl.bind(ServerImpl.java:133)


	at sun.net.httpserver.HttpServerImpl.bind(HttpServerImpl.java:54)


	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer.<init>(HTTPServer.java:145)


	at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:49)


FATAL ERROR in native method: processing of -javaagent failed


	... 6 more


Exception in thread "main" java.lang.reflect.InvocationTargetException


	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)


	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)


	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


	at java.lang.reflect.Method.invoke(Method.java:498)


	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)


	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)


Caused by: java.net.BindException: Address in use


	at sun.nio.ch.Net.bind0(Native Method)


	at sun.nio.ch.Net.bind(Net.java:433)


	at sun.nio.ch.Net.bind(Net.java:425)


	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)


	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)


	at sun.net.httpserver.ServerImpl.bind(ServerImpl.java:133)


	at sun.net.httpserver.HttpServerImpl.bind(HttpServerImpl.java:54)


	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer.<init>(HTTPServer.java:145)


	at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:49)


	... 6 more


FATAL ERROR in native method: processing of -javaagent failed


Exception in thread "main" java.lang.reflect.InvocationTargetException


	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)


	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)


	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


	at java.lang.reflect.Method.invoke(Method.java:498)


	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)


	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)


Caused by: java.net.BindException: Address in use


	at sun.nio.ch.Net.bind0(Native Method)


	at sun.nio.ch.Net.bind(Net.java:433)


	at sun.nio.ch.Net.bind(Net.java:425)


	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)


	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)


	at sun.net.httpserver.ServerImpl.bind(ServerImpl.java:133)


	at sun.net.httpserver.HttpServerImpl.bind(HttpServerImpl.java:54)


	at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer.<init>(HTTPServer.java:145)


	at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:49)


	... 6 more


FATAL ERROR in native method: processing of -javaagent failed


/usr/bin/create-topics.sh: line 57:   524 Aborted                 (core dumped) JMX_PORT='' /opt/kafka/bin/kafka-topics.sh --create --zookeeper zookeeper_service:2181 --topic mytopic_box_device_event --partitions 5 --replication-factor 1 --if-not-exists


/usr/bin/create-topics.sh: line 57:   525 Aborted                 (core dumped) JMX_PORT='' /opt/kafka/bin/kafka-topics.sh --create --zookeeper zookeeper_service:2181 --topic mytopic_box_status_event --partitions 5 --replication-factor 1 --if-not-exists



/usr/bin/create-topics.sh: line 57:   526 Aborted                 (core dumped) JMX_PORT='' /opt/kafka/bin/kafka-topics.sh --create --zookeeper zookeeper_service:2181 --topic mytopic_box_reply_event --partitions 5 --replication-factor 1 --if-not-exists

```

**Comment by sscaling** [comment]
Same reason as https://github.com/wurstmeister/kafka-docker/wiki#why-do-kafka-tools-fail-when-jmx-is-enabled.

You'll need to unset JMX_OPTS / use a separate container that isn't already running the agent.

**Comment by akdj** [comment]
Hi, 

I succeed by adding 
 ```      EXTRA_ARGS: "-javaagent:/opt/jmx/jmx_prometheus_javaagent-0.3.1.jar=7778:/opt/jmx/jmx_config.yml "
```
