### ISSUE TITLE
ERROR Disk error while locking directory /kafka/kafka-logs-ec7ed0df5db9

### ISSUE THREAD

**Issue by sjblom** [wurstmeister/kafka-docker#436]
Hi there,

Can someone please assist, I'm experiencing the following when trying to run the "wurstmeister/kafka" image.

Please bear with me, I'm very new at the docker thing, I just need some guidence.

The error I'm getting is:

```
[2018-12-04 15:23:21,547] ERROR Disk error while locking directory /kafka/kafka-logs-ec7ed0df5db9 (kafka.server.LogDirFailureChannel)
java.io.IOException: Not supported
at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:90)
at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1115)
at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
at kafka.utils.FileLock.tryLock(FileLock.scala:54)
at kafka.log.LogManager.$anonfun$lockLogDirs$1(LogManager.scala:239)
at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
at kafka.log.LogManager.lockLogDirs(LogManager.scala:236)
at kafka.log.LogManager.<init>(LogManager.scala:97)
at kafka.log.LogManager$.apply(LogManager.scala:1005)
at kafka.server.KafkaServer.startup(KafkaServer.scala:237)
at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
at kafka.Kafka$.main(Kafka.scala:75)
at kafka.Kafka.main(Kafka.scala)
[2018-12-04 15:23:21,568] INFO Loading logs. (kafka.log.LogManager)
[2018-12-04 15:23:21,595] INFO Logs loading complete in 27 ms. (kafka.log.LogManager)
[2018-12-04 15:23:21,619] INFO Starting log cleanup with a period of 300000 ms. (kafka.log.LogManager)
[2018-12-04 15:23:21,628] INFO Starting log flusher with a default period of 9223372036854775807 ms. (kafka.log.LogManager)
[2018-12-04 15:23:22,611] INFO Awaiting socket connections on 0.0.0.0:9092. (kafka.network.Acceptor)
[2018-12-04 15:23:22,665] INFO [SocketServer brokerId=1005] Started 1 acceptor threads (kafka.network.SocketServer)
[2018-12-04 15:23:22,694] INFO [ExpirationReaper-1005-Produce]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2018-12-04 15:23:22,701] INFO [ExpirationReaper-1005-Fetch]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2018-12-04 15:23:22,703] INFO [ExpirationReaper-1005-DeleteRecords]: Starting (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2018-12-04 15:23:22,735] INFO [LogDirFailureHandler]: Starting (kafka.server.ReplicaManager$LogDirFailureHandler)
[2018-12-04 15:23:22,740] INFO [ReplicaManager broker=1005] Stopping serving replicas in dir /kafka/kafka-logs-ec7ed0df5db9 (kafka.server.ReplicaManager)
[2018-12-04 15:23:22,752] INFO [ReplicaFetcherManager on broker 1005] Removed fetcher for partitions Set() (kafka.server.ReplicaFetcherManager)
[2018-12-04 15:23:22,753] INFO [ReplicaAlterLogDirsManager on broker 1005] Removed fetcher for partitions Set() (kafka.server.ReplicaAlterLogDirsManager)
[2018-12-04 15:23:22,778] INFO [ReplicaManager broker=1005] Broker 1005 stopped fetcher for partitions  and stopped moving logs for partitions  because they are in the failed log directory /kafka/kafka-logs-ec7ed0df5db9. (kafka.server.ReplicaManager)
[2018-12-04 15:23:22,779] INFO Stopping serving logs in dir /kafka/kafka-logs-ec7ed0df5db9 (kafka.log.LogManager)
[2018-12-04 15:23:22,783] ERROR Shutdown broker because all log dirs in /kafka/kafka-logs-ec7ed0df5db9 have failed (kafka.log.LogManager)
```

I'm running "Docker Desktop" on a Windows 10 machine, on "Windows Containers"

Thank you

**Comment by sscaling** [comment]
I would suggest posting your configuration and steps that you have taken to produce the error. Given that your on your 5th auto-generated broker-ID i'm guessing things have been restarted several times in a non-clean way.

I'd try a `docker-compose down -v` or `docker-compose rm -vfs` to clear state of all the containers and start again.

**Comment by sjblom** [comment]
Here's the config section:

`{
            "Hostname": "7278aadeee26",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "KAFKA_AUTO_CREATE_TOPICS_ENABLE=false",
                "KAFKA_ZOOKEEPER_CONNECT=172.29.169.120:2181",
                "KAFKA_ADVERTISED_HOST_NAME=172.29.169.119",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin:/opt/kafka/bin",
                "LANG=C.UTF-8",
                "JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk/jre",
                "JAVA_VERSION=8u181",
                "JAVA_ALPINE_VERSION=8.181.13-r0",
                "KAFKA_VERSION=2.1.0",
                "SCALA_VERSION=2.12",
                "KAFKA_HOME=/opt/kafka",
                "GLIBC_VERSION=2.28-r0",
                "KAFKA_HEAP_OPTS=-Xmx256M -Xms256M"
            ],
            "Cmd": [
                "start-kafka.sh"
            ],
            "ArgsEscaped": true,
            "Image": "wurstmeister/kafka",
            "Volumes": {
                "/kafka": {}
            },
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "maintainer": "wurstmeister",
                "org.label-schema.build-date": "2018-11-22T08:54:14Z",
                "org.label-schema.description": "Apache Kafka",
                "org.label-schema.name": "kafka",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-ref": "84b3e08dd798bf1fdd0a04a882f322aad31946d6",
                "org.label-schema.vcs-url": "https://github.com/wurstmeister/kafka-docker",
                "org.label-schema.version": "2.12_2.1.0"
            }
        }`

**Comment by sjblom** [comment]
Thank you @sscaling ,

I'll give it a try tomorrow. Will keep this thread open, for some feedback.

Much appreciated

**Comment by sscaling** [comment]
One thing that is strange is the `sun.nio.ch.FileDispatcherImpl.lock0(Native Method) ...  Not supported` error. I think if the problem is not consistently reproducible, then I suspect it's trying to allocate more memory than available. In Java land an OOM Error is classed as undefined and not safe to recover from. 

So this may all go away if you consistently set the Xmx options from the start and/or allocate enough memory to the docker daemon.

**Comment by sscaling** [comment]
@sjblom - any luck? Can this be closed?

**Comment by sscaling** [comment]
Closing as no response from OP.

**Comment by sjblom** [comment]
My bad...

Sorry for the delay...
Yes, I was able to get past this, by running docker on a Linux container...

The Windows containers aren't working...
