### ISSUE TITLE
Request METADATA failed on brokers List

### ISSUE THREAD

**Issue by junaidrazzaq323** [wurstmeister/kafka-docker#460]
I am using `wurstmeister/kafka:2.12-2.1.0` docker image and running it in a kubernetes setup. I am using `kafka-broker-api-versions.sh --bootstrap-server localhost:9092` as a readiness probe. However, I get the following exception:

```
Exception in thread "main" java.lang.RuntimeException: Request METADATA failed on brokers List(localhost:9092 (id: -1 rack: null))
	at kafka.admin.AdminClient.sendAnyNode(AdminClient.scala:106)
	at kafka.admin.AdminClient.findAllBrokers(AdminClient.scala:164)
	at kafka.admin.AdminClient.awaitBrokers(AdminClient.scala:156)
	at kafka.admin.BrokerApiVersionsCommand$.execute(BrokerApiVersionsCommand.scala:42)
	at kafka.admin.BrokerApiVersionsCommand$.main(BrokerApiVersionsCommand.scala:36)
	at kafka.admin.BrokerApiVersionsCommand.main(BrokerApiVersionsCommand.scala)

```

Can you please help me out in figuring out what the issue here might be.

Thanks

**Comment by sscaling** [comment]
I suspect if you want help with this issue you will need to provide more information such as your configuration, kubernetes setup info (version etc), debugging steps taken so far. 

From the description I've no idea what configuration you are running (i.e. what NICs / ports the listeners are bound to).

If I don't hear back in a few days, I'll close the issue.

**Comment by sscaling** [comment]
* Do you get the same response, if you remove the `readinessProbe` from kafka and execute the command manually from inside the container?
* What interface is Kafka bound to?
* Is meta-data registered in zookeeper? If so, what does it look like?

**Comment by junaidrazzaq323** [comment]
1) Yes, I get the same error when I exec into the container and run the command manually.
2)  I think Kafka is bound to default interface. I have't changed any configs related to this.
3) I exec into zookeeper and run the CLI using zkCli.sh script:
> `ls /brokers/topics` gives me a list of topics.
> `ls /brokers/ids` gives me a one broker. Output: `[1]`

**Comment by sscaling** [comment]
> 1\. Yes, I get the same error when I exec into the container and run the command manually
> 2\. I think Kafka is bound to default interface

Right - I would still recommend checking what the default interface is. `netstat` should be your friend here, something like

```
bash-4.4# netstat -ntap | grep 9092
tcp        0      0 0.0.0.0:9092            0.0.0.0:*               LISTEN      1/java
tcp        0      0 172.29.0.2:9092         172.29.0.1:49260        ESTABLISHED 1/java
```

If the port is bound (I seem to think it binds quite early in Kafka) then the service itself may not be available - hence the failure of the readinessProbe.

If you look at the service logs did it start successfully (should have a line such as `INFO [KafkaServer id=1001] started (kafka.server.KafkaServer)`) or are there a lot of error messages?

> `> ls /brokers/ids` gives me a one broker. Output: `[1]`

So something more interesting is `get /broker/ids/1` which will show you the registered metadata for the broker. Does this look correct for your configuration? You should also be able to grep the logs for the configured values,

```
docker-compose logs kafka | egrep 'advertised|host.name|port|listener' | sort | uniq
```

Without a set of steps and clear configs to reproduce your issue, it's a bit hard to offer any further help. At this point it looks like a configuration issue.

With a simple config this works fine

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.0.3"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

from inside the container

```
bash-4.4# kafka-broker-api-versions.sh --bootstrap-server localhost:9092
192.168.0.3:32770 (id: 1001 rack: null) -> (
	Produce(0): 0 to 7 [usable: 7],
	Fetch(1): 0 to 10 [usable: 10],
	ListOffsets(2): 0 to 4 [usable: 4],
	Metadata(3): 0 to 7 [usable: 7],
	LeaderAndIsr(4): 0 to 1 [usable: 1],
	StopReplica(5): 0 [usable: 0],
	UpdateMetadata(6): 0 to 4 [usable: 4],
	ControlledShutdown(7): 0 to 1 [usable: 1],
	OffsetCommit(8): 0 to 6 [usable: 6],
	OffsetFetch(9): 0 to 5 [usable: 5],
	FindCoordinator(10): 0 to 2 [usable: 2],
	JoinGroup(11): 0 to 3 [usable: 3],
	Heartbeat(12): 0 to 2 [usable: 2],
	LeaveGroup(13): 0 to 2 [usable: 2],
	SyncGroup(14): 0 to 2 [usable: 2],
	DescribeGroups(15): 0 to 2 [usable: 2],
	ListGroups(16): 0 to 2 [usable: 2],
	SaslHandshake(17): 0 to 1 [usable: 1],
	ApiVersions(18): 0 to 2 [usable: 2],
	CreateTopics(19): 0 to 3 [usable: 3],
	DeleteTopics(20): 0 to 3 [usable: 3],
	DeleteRecords(21): 0 to 1 [usable: 1],
	InitProducerId(22): 0 to 1 [usable: 1],
	OffsetForLeaderEpoch(23): 0 to 2 [usable: 2],
	AddPartitionsToTxn(24): 0 to 1 [usable: 1],
	AddOffsetsToTxn(25): 0 to 1 [usable: 1],
	EndTxn(26): 0 to 1 [usable: 1],
	WriteTxnMarkers(27): 0 [usable: 0],
	TxnOffsetCommit(28): 0 to 2 [usable: 2],
	DescribeAcls(29): 0 to 1 [usable: 1],
	CreateAcls(30): 0 to 1 [usable: 1],
	DeleteAcls(31): 0 to 1 [usable: 1],
	DescribeConfigs(32): 0 to 2 [usable: 2],
	AlterConfigs(33): 0 to 1 [usable: 1],
	AlterReplicaLogDirs(34): 0 to 1 [usable: 1],
	DescribeLogDirs(35): 0 to 1 [usable: 1],
	SaslAuthenticate(36): 0 [usable: 0],
	CreatePartitions(37): 0 to 1 [usable: 1],
	CreateDelegationToken(38): 0 to 1 [usable: 1],
	RenewDelegationToken(39): 0 to 1 [usable: 1],
	ExpireDelegationToken(40): 0 to 1 [usable: 1],
	DescribeDelegationToken(41): 0 to 1 [usable: 1],
	DeleteGroups(42): 0 to 1 [usable: 1]
)

```

It is also worth nothing that an unresolvable / bogus address results in the same error as what you are seeing:

```
bash-4.4# kafka-broker-api-versions.sh --bootstrap-server foobar:9092
Exception in thread "main" java.lang.RuntimeException: Request METADATA failed on brokers List(foobar:9092 (id: -1 rack: null))
	at kafka.admin.AdminClient.sendAnyNode(AdminClient.scala:106)
	at kafka.admin.AdminClient.findAllBrokers(AdminClient.scala:164)
	at kafka.admin.AdminClient.awaitBrokers(AdminClient.scala:156)
	at kafka.admin.BrokerApiVersionsCommand$.execute(BrokerApiVersionsCommand.scala:42)
	at kafka.admin.BrokerApiVersionsCommand$.main(BrokerApiVersionsCommand.scala:36)
	at kafka.admin.BrokerApiVersionsCommand.main(BrokerApiVersionsCommand.scala)
```

**Comment by junaidrazzaq323** [comment]
Thank you so much for all the help so far. I have tried two things, the details of which are below.

**First:**
I tried debugging the issue using your guidelines. Running with the same configs as before.

`> kubectl exec -it kafkaservice-5c4ff79889-b7pxk -n casb-deployment bash`
`> netstat -ntap | grep 9092`
Output:
```
tcp        0      0 0.0.0.0:9092            0.0.0.0:*               LISTEN      1/java
tcp        0      0 127.0.0.1:35392         127.0.0.1:9092          TIME_WAIT   -
tcp        0      0 127.0.0.1:35324         127.0.0.1:9092          TIME_WAIT   -
tcp        0      0 127.0.0.1:35290         127.0.0.1:9092          TIME_WAIT   -
tcp        0      0 127.0.0.1:35488         127.0.0.1:9092          ESTABLISHED 11753/java
tcp        0      0 127.0.0.1:35422         127.0.0.1:9092          TIME_WAIT   -
tcp        0     48 127.0.0.1:9092          127.0.0.1:35488         ESTABLISHED 1/java
tcp        0      0 127.0.0.1:35456         127.0.0.1:9092          TIME_WAIT   -
tcp        0      0 127.0.0.1:35358         127.0.0.1:9092          TIME_WAIT   -
```
after a while this changed to:
```
tcp        0      0 0.0.0.0:9092            0.0.0.0:*               LISTEN      1/java
tcp        0      0 127.0.0.1:37098         127.0.0.1:9092          ESTABLISHED 14678/java
tcp        0     48 127.0.0.1:9092          127.0.0.1:36414         ESTABLISHED 1/java
tcp        0      0 127.0.0.1:36648         127.0.0.1:9092          ESTABLISHED 14096/java
tcp        0      0 127.0.0.1:36172         127.0.0.1:9092          ESTABLISHED 12664/java
tcp        0     48 127.0.0.1:9092          127.0.0.1:35954         ESTABLISHED 1/java
tcp        0     48 127.0.0.1:9092          127.0.0.1:37098         ESTABLISHED 1/java
tcp        0      0 127.0.0.1:36872         127.0.0.1:9092          ESTABLISHED 14383/java
tcp        0     48 127.0.0.1:9092          127.0.0.1:35714         ESTABLISHED 1/java
tcp        0      0 127.0.0.1:35488         127.0.0.1:9092          ESTABLISHED 11753/java
tcp        0      0 127.0.0.1:35714         127.0.0.1:9092          ESTABLISHED 12067/java
tcp        0      0 127.0.0.1:36414         127.0.0.1:9092          ESTABLISHED 13239/java
tcp        0     48 127.0.0.1:9092          127.0.0.1:35488         ESTABLISHED 1/java
tcp        0      0 127.0.0.1:37316         127.0.0.1:9092          ESTABLISHED 14965/java
tcp        0     48 127.0.0.1:9092          127.0.0.1:37316         ESTABLISHED 1/java
tcp        0     48 127.0.0.1:9092          127.0.0.1:36172         ESTABLISHED 1/java
tcp        0      0 127.0.0.1:9092          127.0.0.1:36872         ESTABLISHED 1/java
tcp        0      0 127.0.0.1:35954         127.0.0.1:9092          ESTABLISHED 12377/java
tcp        0     48 127.0.0.1:9092          127.0.0.1:36648         ESTABLISHED 1/java
```

Running `kubectl logs -f kafkaservice-5c4ff79889-b7pxk -n casb-deployment | grep advertised` command gives:
```
advertised.host.name = kafkaservice
advertised.listeners = null
advertised.port = null
```
Next I exec into kafka pod and do `cd /opt/kafka/bin` and run 
`kafka-broker-api-versions.sh --bootstrap-server=localhost:9092` and 
`kafka-broker-api-versions.sh --bootstrap-server=kafkaservice:9092`. 
In both cases it keeps waiting for output but nothing is returned.
However, running `kubectl describe pod kafkaservice-5c4ff79889-b7pxk -n casb-deployment` shows:
```
Events:
  Type     Reason                 Age                 From                            Message
  ----     ------                 ----                ----                            -------
  Normal   Scheduled              12m                 default-scheduler               Successfully assigned kafkaservice-5c4ff79889-b7pxk to localhost.localdomain
  Normal   SuccessfulMountVolume  12m                 kubelet, localhost.localdomain  MountVolume.SetUp succeeded for volume "kafka-volume"
  Normal   SuccessfulMountVolume  12m                 kubelet, localhost.localdomain  MountVolume.SetUp succeeded for volume "default-token-4kzv6"
  Normal   Pulled                 12m                 kubelet, localhost.localdomain  Container image "zookeeper:3.3.6" already present on machine
  Normal   Created                12m                 kubelet, localhost.localdomain  Created container
  Normal   Started                12m                 kubelet, localhost.localdomain  Started container
  Normal   Pulled                 12m                 kubelet, localhost.localdomain  Container image "wurstmeister/kafka:2.12-2.1.0" already present on machine
  Normal   Created                12m                 kubelet, localhost.localdomain  Created container
  Normal   Started                11m                 kubelet, localhost.localdomain  Started container
  Warning  Unhealthy              10m (x11 over 11m)  kubelet, localhost.localdomain  Readiness probe failed: Exception in thread "main" java.lang.RuntimeException: Request METADATA failed on brokers List(localhost:9092 (id: -1 rack: null))
           at kafka.admin.AdminClient.sendAnyNode(AdminClient.scala:106)
           at kafka.admin.AdminClient.findAllBrokers(AdminClient.scala:164)
           at kafka.admin.AdminClient.awaitBrokers(AdminClient.scala:156)
           at kafka.admin.BrokerApiVersionsCommand$.execute(BrokerApiVersionsCommand.scala:42)
           at kafka.admin.BrokerApiVersionsCommand$.main(BrokerApiVersionsCommand.scala:36)
           at kafka.admin.BrokerApiVersionsCommand.main(BrokerApiVersionsCommand.scala)
  Warning  Unhealthy  3m  kubelet, localhost.localdomain  Readiness probe errored: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```
Next I tried `get /brokers/ids/1` inside zookeeper pod and it gives out the following output:
```
{"listener_security_protocol_map":{"PLAINTEXT":"PLAINTEXT"},"endpoints":["PLAINTEXT://kafkaservice:9092"],"jmx_port":-1,"host":"kafkaservice","timestamp":"1549985633131","port":9092,"version":4}
cZxid = 0x18
ctime = Tue Feb 12 15:33:53 GMT 2019
mZxid = 0x18
mtime = Tue Feb 12 15:33:53 GMT 2019
pZxid = 0x18
cversion = 0
dataVersion = 0
aclVersion = 0
ephemeralOwner = 0x168e2577baa0000
dataLength = 194
numChildren = 0
```

**Second:**

I changed zookeeper image from official to `wurstmeister/zookeeper:3.4.6`
Then I run zookeeper and kafka with the following configs (these are the same as before) : 
```
env:
 - name: KAFKA_BROKER_ID
   value: "1"
 - name: KAFKA_ADVERTISED_HOST_NAME
   value: "kafkaservice"
 - name: KAFKA_CREATE_TOPICS
```

Running `kubectl logs -f kafkaservice-5c4ff79889-54rsx -n casb-deployment | grep advertised` command gives:
```
advertised.host.name = kafkaservice
advertised.listeners = null
advertised.port = null
```
Next I exec into kafka pod using `kubectl exec -it kafkaservice-5c4ff79889-54rsx -n casb-deployment bash` and run `netstat -ntap | grep 9092` which gives the following output:

```
tcp        0      0 0.0.0.0:9092            0.0.0.0:*               LISTEN      1/java
tcp        0      0 127.0.0.1:60970         127.0.0.1:9092          TIME_WAIT   -
tcp        1      0 192.168.13.89:36410     192.168.13.89:9092      CLOSE_WAIT  1/java
tcp        0      0 192.168.13.89:41168     192.168.13.89:9092      TIME_WAIT   -
tcp        0      0 127.0.0.1:60904         127.0.0.1:9092          TIME_WAIT   -
tcp        0      0 192.168.13.89:41146     192.168.13.89:9092      TIME_WAIT   -
tcp        0      0 127.0.0.1:60860         127.0.0.1:9092          TIME_WAIT   -
tcp        0      0 192.168.13.89:41190     192.168.13.89:9092      TIME_WAIT   -
tcp        0      0 192.168.13.89:41124     192.168.13.89:9092      TIME_WAIT   -
tcp        0      0 192.168.13.89:41212     192.168.13.89:9092      TIME_WAIT   -
tcp        0      0 127.0.0.1:60948         127.0.0.1:9092          TIME_WAIT   -
tcp        0      0 127.0.0.1:60882         127.0.0.1:9092          TIME_WAIT   -
tcp        0      0 192.168.13.89:41102     192.168.13.89:9092      TIME_WAIT   -
tcp        0      0 127.0.0.1:60926         127.0.0.1:9092          TIME_WAIT   -

```

Next `cd /opt/kafka/bin` and Now when I run `kafka-broker-api-versions.sh --bootstrap-server=localhost:9092` I get the following output:
```
kafkaservice:9092 (id: 1 rack: null) -> (
	Produce(0): 0 to 7 [usable: 7],
	Fetch(1): 0 to 10 [usable: 10],
	ListOffsets(2): 0 to 4 [usable: 4],
	Metadata(3): 0 to 7 [usable: 7],
	LeaderAndIsr(4): 0 to 1 [usable: 1],
	StopReplica(5): 0 [usable: 0],
	UpdateMetadata(6): 0 to 4 [usable: 4],
	ControlledShutdown(7): 0 to 1 [usable: 1],
	OffsetCommit(8): 0 to 6 [usable: 6],
	OffsetFetch(9): 0 to 5 [usable: 5],
	FindCoordinator(10): 0 to 2 [usable: 2],
	JoinGroup(11): 0 to 3 [usable: 3],
	Heartbeat(12): 0 to 2 [usable: 2],
	LeaveGroup(13): 0 to 2 [usable: 2],
	SyncGroup(14): 0 to 2 [usable: 2],
	DescribeGroups(15): 0 to 2 [usable: 2],
	ListGroups(16): 0 to 2 [usable: 2],
	SaslHandshake(17): 0 to 1 [usable: 1],
	ApiVersions(18): 0 to 2 [usable: 2],
	CreateTopics(19): 0 to 3 [usable: 3],
	DeleteTopics(20): 0 to 3 [usable: 3],
	DeleteRecords(21): 0 to 1 [usable: 1],
	InitProducerId(22): 0 to 1 [usable: 1],
	OffsetForLeaderEpoch(23): 0 to 2 [usable: 2],
	AddPartitionsToTxn(24): 0 to 1 [usable: 1],
	AddOffsetsToTxn(25): 0 to 1 [usable: 1],
	EndTxn(26): 0 to 1 [usable: 1],
	WriteTxnMarkers(27): 0 [usable: 0],
	TxnOffsetCommit(28): 0 to 2 [usable: 2],
	DescribeAcls(29): 0 to 1 [usable: 1],
	CreateAcls(30): 0 to 1 [usable: 1],
	DeleteAcls(31): 0 to 1 [usable: 1],
	DescribeConfigs(32): 0 to 2 [usable: 2],
	AlterConfigs(33): 0 to 1 [usable: 1],
	AlterReplicaLogDirs(34): 0 to 1 [usable: 1],
	DescribeLogDirs(35): 0 to 1 [usable: 1],
	SaslAuthenticate(36): 0 [usable: 0],
	CreatePartitions(37): 0 to 1 [usable: 1],
	CreateDelegationToken(38): 0 to 1 [usable: 1],
	RenewDelegationToken(39): 0 to 1 [usable: 1],
	ExpireDelegationToken(40): 0 to 1 [usable: 1],
	DescribeDelegationToken(41): 0 to 1 [usable: 1],
	DeleteGroups(42): 0 to 1 [usable: 1]
)

```
**This also yields in a successful readiness probe.**

I also tried `ls /brokers/ids/1` inside zookeeper pod and it gives out the same output as before:
```
{"listener_security_protocol_map":{"PLAINTEXT":"PLAINTEXT"},"endpoints":["PLAINTEXT://kafkaservice:9092"],"jmx_port":-1,"host":"kafkaservice","timestamp":"1549987555784","port":9092,"version":4}
cZxid = 0x18
ctime = Tue Feb 12 16:05:55 UTC 2019
mZxid = 0x18
mtime = Tue Feb 12 16:05:55 UTC 2019
pZxid = 0x18
cversion = 0
dataVersion = 0
aclVersion = 0
ephemeralOwner = 0x168e274f98c0000
dataLength = 194
numChildren = 0
```

Now, I can either change zookeeper image from official `(zookeeper:3.3.6)` to `wurstmeister/zookeeper:3.4.6` OR I can continue exploring the root cause of the issue with zookeeper:3.3.6 image.

If you can help me debug this by giving some more pointers then that would be great.

Again, Thanks for all the help.
