### ISSUE TITLE
ERROR: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version

### ISSUE THREAD

**Issue by wenfengsui** [wurstmeister/kafka-docker#461]
the error happened after upgrade window docker desktop to the latest.

the workaround is increase version of docker-compose file.

**Comment by wenfengsui** [comment]
i have created pull request https://github.com/wurstmeister/kafka-docker/pull/462

**Comment by sscaling** [comment]
This is error message would indicate a client error, not a docker compose version error. I would expect upgrading your docker client is the required fix, not changing the docker compose version. Version '2.0' has been supported from docker engine `1.10.0` onwards. ref: https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix

I am curious why upgrading the docker-compose version appears to fix this for you? Perhaps a bug in the windows client implementation?

**Comment by sscaling** [comment]
A quick google finds similar issues which indicate a bug in the Windows implementation. Did you try anything like 'Switch to linux containers' (https://github.com/docker/compose/issues/4106#issuecomment-356443809) ?

**Comment by HQebupt** [comment]
'Switch to linux containers' does not work. It will occure an error:
`Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'CNENHUANGQ1L2C' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass28_0.<SwitchDaemon>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 305
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59`

**Comment by sscaling** [comment]
@HQebupt - sounds like a Docker on windows issue rather than anything to do with this image.

**Comment by MartinBeseda** [comment]
Hello,
I have the very same problem - `docker version` prints this

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:28:48 2019
  OS/Arch:          windows/amd64
  Experimental:     false
```

And I'm still getting the error message 
`ERROR: Preparation failed: Error response from daemon: client version 1.18 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version (executor_docker.go:1164:0s)`

I've also tried to add `version: '3.3'` into `docker-compose.yml`, but with no success...

**Comment by cbaurand** [comment]
It's still not working. Any news about this problem?

**Comment by MeCrazyJunkie** [comment]
> It's still not working. Any news about this problem?

put in the head of docker-compose:

`version: '2.4'`

it helped me

**Comment by iNithinPrasad** [comment]
You have 2 options here

1.  Check if you are using the wrong/incompatible OS for the image. If so switch your OS in docker desktop and try once more. 
2. Change the docker compose version tag to 2.4 as the original version is not updated.

**Comment by srungta** [comment]
It started working for me after switching to Linux containers on Win 10

**Comment by filatan** [comment]
> A quick google finds similar issues which indicate a bug in the Windows implementation. Did you try anything like 'Switch to linux containers' ([docker/compose#4106 (comment)](https://github.com/docker/compose/issues/4106#issuecomment-356443809)) ?

This worked fine for me...Thanks

**Comment by sahumino** [comment]
> i have created pull request #462

This solution saved my day. Thank you.

**Comment by wbanchon** [comment]
> > Todavía no funciona. ¿Alguna noticia sobre este problema?
> 
> poner en la cabeza de docker-compose:
> 
> `version: '2.4'`
> 
> Me ayudó

Perfecto, esto funcionó en un ambiente de Linux

**Comment by bendene12** [comment]
Thank you @StayHomeThereIsNoFrance ! 
Your suggestion worked for me big time!
