### ISSUE TITLE
kafka.errors.NoBrokersAvailable: NoBrokersAvailable

### ISSUE THREAD

**Issue by yueyuan4** [wurstmeister/kafka-docker#491]
I did this in order
1. modify the KAFKA_ADVERTISED_HOST_NAME in docker-compose.yml 
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.31.236.172
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

```
2.`docker-compose up -d`
3.`docker-compose scale kafka=3`
4.`docker ps|grep kafka`
```
11048a70c5d4        wurstmeister/kafka                         "/bin/bash"              31 minutes ago      Up 31 minutes                                                                                                                                              sharp_lalande
b8c39da3bd65        wurstmeister/kafka                         "/bin/bash"              34 minutes ago      Up 34 minutes                                                                                                                                              sharp_tesla
b3e335e9be34        kafka-docker_kafka                         "start-kafka.sh"         40 minutes ago      Up 40 minutes       0.0.0.0:32780->9092/tcp                                                                                                                kafka-docker_kafka_2
65baf2f3423a        kafka-docker_kafka                         "start-kafka.sh"         40 minutes ago      Up 40 minutes       0.0.0.0:32779->9092/tcp                                                                                                                kafka-docker_kafka_3
9aa6cbd6a8f5        kafka-docker_kafka                         "start-kafka.sh"         40 minutes ago      Up 40 minutes       0.0.0.0:32778->9092/tcp                                                                                                                kafka-docker_kafka_1
824bdb7b4281        wurstmeister/zookeeper                     "/bin/sh -c '/usr/sb…"   2 hours ago         Up 40 minutes       22/tcp, 2888/tcp, 3888/tcp, 0.0.0.0:2181->2181/tcp                                                                                     kafka-docker_zookeeper_1

```
5.producer
`./start-kafka-shell.sh 172.31.236.172 172.31.236.172:2181`
```
$KAFKA_HOME/bin/kafka-topics.sh --create --topic topic  --partitions 4 --zookeeper $ZK --replication-factor 2
Created topic "topic".
```
```
$KAFKA_HOME/bin/kafka-topics.sh --describe --topic topic --zookeeper $ZK
Topic:topic	PartitionCount:4	ReplicationFactor:2	Configs:
	Topic: topic	Partition: 0	Leader: 1010	Replicas: 1010,1011	Isr: 1010,1011
	Topic: topic	Partition: 1	Leader: 1011	Replicas: 1011,1012	Isr: 1011,1012
	Topic: topic	Partition: 2	Leader: 1012	Replicas: 1012,1010	Isr: 1012,1010
	Topic: topic	Partition: 3	Leader: 1010	Replicas: 1010,1012	Isr: 1010,1012
```
`$KAFKA_HOME/bin/kafka-console-producer.sh --topic=topic  --broker-list=`broker-list.sh``

6.consumer
`$KAFKA_HOME/bin/kafka-console-consumer.sh --topic=topic --bootstrap-server=172.31.236.172:32780,172.31.236.172:32779,172.31.236.172:32778`

I find it can product and consume,but I got "NoBrokersAvailable" in my python code running on my computor

```
from kafka import KafkaProducer


if __name__ == '__main__':
    producer = KafkaProducer(bootstrap_servers=['172.16.236.172:32780','172.16.236.172:32779','172.16.236.172:32778'])
    future = producer.send('topic', key= b'my_key', value= b'my_value', partition= 0)
    result = future.get(timeout= 10)
    print(result)
```
```
Traceback (most recent call last):
  File "F:/workspacePython/mofei/oauth/kafka_producer.py", line 5, in <module>
    producer = KafkaProducer(bootstrap_servers=['172.16.236.172:32780','172.16.236.172:32779','172.16.236.172:32778'])
  File "F:\developer_tools\python27\lib\site-packages\kafka\producer\kafka.py", line 381, in __init__
    **self.config)
  File "F:\developer_tools\python27\lib\site-packages\kafka\client_async.py", line 239, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "F:\developer_tools\python27\lib\site-packages\kafka\client_async.py", line 892, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
```

**Comment by sscaling** [comment]
Looking at your `kafka-topics` output, I'd suggest you have been restarting kafka without removing state in zookeeper

> Leader: 1010

Automatic leader IDs start at 1000 (see [https://kafka.apache.org/documentation/#brokerconfigs] - `reserved.broker.max.id` / `broker.id` documentation etc).

I'd expect if you start from a clean slate, things would work as expected, i.e.

```
docker-compose down -v
docker-compose up -d
docker-compose scale kafka=3
```

However, If the Kafka console consumer/producer tools are working it would indicate an issue in the Python code. I'd suggest opening a bug with the library owners. 

Please re-open if you can provide concrete steps to show that the Kafka image contains a bug. Thanks.
