### ISSUE TITLE
while running kafka docker in aws and creating topic and trying to send message i am getting this error

### ISSUE THREAD

**Issue by rishavjaiswal** [wurstmeister/kafka-docker#507]
[2019-06-07 10:08:27,415] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 20 : {test1=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-07 10:08:27,505] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 21 : {test1=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-07 10:08:27,612] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 22 : {test1=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)

**Comment by sscaling** [comment]
You'd need to provide steps and assets to reproduce the issue, i.e. docker-compose files, commands used to reproduce. Also things like logs, versions of docker, host OS etc would give people the best chance of trying to help you.

**Comment by rishavjaiswal** [comment]
**docker-compose up -d**
       Starting kafka-docker_zookeeper_1 ... done
       Starting kafka-docker_kafka_1     ... done
**docker container ls**
      CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                                NAMES
1dc8c93d623d        kafka-docker_kafka       "start-kafka.sh"         3 hours ago         Up 8 minutes        0.0.0.0:32770->9092/tcp                              kafka-docker_kafka_1
1b2c4aed2e56        wurstmeister/zookeeper   "/bin/sh -c '/usr/..."   3 hours ago         Up 8 minutes        22/tcp, 2888/tcp, 3888/tcp, 0.0.0.0:2181->2181/tcp   kafka-docker_zookeeper_1

**docker exec -it kafka-docker_kafka_1 bash**
**bash-4.4# kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic test**
Created topic test.

**bash-4.4# kafka-console-producer.sh --broker-list localhost:9092 --topic test**
>hi
[2019-06-07 09:56:50,823] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 21 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-07 09:56:50,916] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 22 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-07 09:56:51,023] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 23 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-07 09:56:51,130] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 24 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-07 09:56:51,236] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 25 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-07 09:56:51,346] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 26 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-07 09:56:51,452] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 27 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-07 09:56:51,559] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 28 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-07 09:56:51,667] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 29 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)

**Comment by rishavjaiswal** [comment]
[2019-06-08 07:25:04,355] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 46 : {te=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-06-08 07:25:04,461] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 47 : {te=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
^Corg.apache.kafka.common.KafkaException: Producer closed while send in progress
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:869)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:846)
	at kafka.tools.ConsoleProducer$.send(ConsoleProducer.scala:74)
	at kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:56)
	at kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)
Caused by: org.apache.kafka.common.KafkaException: Requested metadata update after close
	at org.apache.kafka.clients.Metadata.awaitUpdate(Metadata.java:271)
	at org.apache.kafka.clients.producer.KafkaProducer.waitOnMetadata(KafkaProducer.java:989)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:866)
	... 4 more

**Comment by rishavjaiswal** [comment]
my docker-compose file content is
:
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 13.235.74.246
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

**Comment by rishavjaiswal** [comment]
i am using aws instance for which public ip is 13.235.74.246
all these operations being carried out in aws ubuntu instance only


please help

**Comment by sscaling** [comment]
Is the firewall (or security groups) blocking the proxied docker port?

**Comment by rishavjaiswal** [comment]
please tell me how the inbound rules in aws security group should look like for my kafka-docker

**Comment by sscaling** [comment]
I would imagine you do not want to open up access, especially given the unsecured Kafka setup you are running. Also if you're not sure how to configure security groups, then I would definitely recommend keeping them restrictive and access closed.

There is an example of using the newer `listener` configurations in the [README](https://github.com/wurstmeister/kafka-docker#listener-configuration) - which is probably better for what you want. 

However, if you are just playing with things and want a single broker kafka instance, just change the `ports` definition to

```
ports:
  - "9092:9092"
```

And that should allow you to proceed.

**Comment by rishavjaiswal** [comment]
i changed the ports to defination to
 kafka:
    build: .
    ports:
      - "9092:9092"
after running
bash-4.4# kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test
eroor:

[2019-06-11 05:03:12,851] WARN [Consumer clientId=consumer-1, groupId=console-consumer-35832] Error while fetching metadata with correlation id 2 : {test=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)

**Comment by rishavjaiswal** [comment]
this is how my inbound rule looks like for aws security group
 
SSH | TCP | 22 | 0.0.0.0/0 |  
Custom TCP Rule | TCP | 9092 | 0.0.0.0/0 |  
Custom TCP Rule | TCP | 9092 | ::/0 |

**Comment by rishavjaiswal** [comment]
is everything right with the command kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test am using ?

**Comment by sscaling** [comment]
* Have you looked at the Kafka logs? Does the broker start up correctly?
* What interface is the broker bound to? if host.name is empty then it should be all interfaces, as per the [docs](https://kafka.apache.org/documentation/)
* You shouldn't need to change your security groups (and would disable access). It's also not a good idea to publish your IP address and ports of a service on the open internet - this makes good reading for malicious folks.

What is your updated docker-compose like? I would expect something like

```
kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by sscaling** [comment]
No response from OP so closing.

**Comment by rishavjaiswal** [comment]
yes my docker-compose looks same

**Comment by rishavjaiswal** [comment]
kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1
--partitions 1 --topic test
kafka-topics.sh is not present in kafka-docker wrustmieter file?

**Comment by sscaling** [comment]
kafka-topics.sh is an artifact provided and packaged by the Apache Kafka binary. Should be included here `/opt/kafka/bin/kafka-topics.sh`

**Comment by rishavjaiswal** [comment]
do i need to install kafka binary explicitly?
wrustmiester kafka-docker does not provide an alternative to send and receive msgs?
