### ISSUE TITLE
Invalid value  for configuration advertised.port: Not a number of type INT

### ISSUE THREAD

**Issue by zollty** [wurstmeister/kafka-docker#521]
I checked all the documents and similar issues, include #170 , #122, but didn't help me.

This is what my configuration looks like (exactly the same as in the [current repo](https://github.com/wurstmeister/kafka-docker/blob/master/docker-compose.yml)）
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

When I run this, the container crashes. These are the logs I see:
```
[2019-07-22 15:41:47,803] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
org.apache.kafka.common.config.ConfigException: Invalid value  for configuration advertised.port: Not a number of type INT
     at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:718)
     at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:473)
     at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:466)
     at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
     at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:142)
     at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1111)
     at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1114)
     at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1094)
     at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
     at kafka.Kafka$.main(Kafka.scala:68)
     at kafka.Kafka.main(Kafka.scala)
```

**Comment by zollty** [comment]
Eventually I found the problem. I record it hope to help others.

I tested the fellow command:
```
bash-4.4# docker port $$(hostname) 9092/tcp | cut -d: -f2
```
got this error:
```
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.22)
```
So I change the client API version, config the docker-compose.yml like this:
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
just add `DOCKER_API_VERSION: 1.22` in the environment, 
then everything went right!
