### ISSUE TITLE
Kakfa report Host is unreachable

### ISSUE THREAD

**Issue by ray0728** [wurstmeister/kafka-docker#572]
Hi all,
I used kafka and zookeeper docker containers in the same time. them are working in the CoreOS, but report exception in CentOS,  I used the same configuration file in these system.
kafka cannot running and report Host is unreachable.
> the java exceptions is:

[2020-02-08 13:36:51,004] INFO Starting ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2020-02-08 13:36:51,037] INFO Waiting for keeper state SyncConnected
(org.I0Itec.zkclient.ZkClient)
[2020-02-08 13:36:51,041] INFO Opening socket connection to server
dev_zookeeper_1.dev_default/172.19.0.3:2181. Will not attempt to authenticate using SASL
(unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-02-08 13:36:52,075] WARN Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.NoRouteToHostException: Host is unreachable
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2020-02-08 13:36:53,189] INFO Opening socket connection to server dev_zookeeper_1.dev_default/172.19.0.3:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-02-08 13:36:54,249] WARN Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.NoRouteToHostException: Host is unreachable
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2020-02-08 13:36:55,351] INFO Opening socket connection to server dev_zookeeper_1.dev_default/172.19.0.3:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-02-08 13:36:56,361] WARN Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.NoRouteToHostException: Host is unreachable
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2020-02-08 13:36:57,038] INFO Terminate ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2020-02-08 13:36:57,463] INFO Opening socket connection to server dev_zookeeper_1.dev_default/172.19.0.3:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-02-08 13:36:58,576] INFO Session: 0x0 closed (org.apache.zookeeper.ZooKeeper)
[2020-02-08 13:36:58,576] FATAL Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server 'zookeeper:2181' with timeout of 6000 ms
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1233)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:157)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:131)
	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:103)
	at kafka.utils.ZkUtils$.apply(ZkUtils.scala:85)
	at kafka.server.KafkaServer.initZk(KafkaServer.scala:338)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:191)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:65)
	at kafka.Kafka.main(Kafka.scala)
[2020-02-08 13:36:58,577] INFO shutting down (kafka.server.KafkaServer)

>My docker-compose.yml is:
 
zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafkaserver:
    image: wurstmeister/kafka:2.11-0.11.0.3
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

>I used docker images are:

REPOSITORY                      TAG                       IMAGE ID               CREATED                  SIZE
wurstmeister/zookeeper   latest                    3f43f72cb283          12 months ago       510MB
gliderlabs/logspout           v3.2.6                    c1bbbb7be686       16 months ago       24.4MB

>docker-compose and docker version are:

docker-compose version
docker-compose version 1.25.3, build d4d1b42b
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

What should I do to make it work? thanks for any help

**Comment by cricket007** [comment]
Based on the error, Zookeeper is not running but you'll also want this to connect to Kafka 

`KAFKA_ADVERTISED_LISTENERS: PLAINTEXT:// localhost:9092`

**Comment by sscaling** [comment]
Closing due to staleness. No response from OP
