### ISSUE TITLE
[swarm] Couldn't match the stored cluster ID - Kafka

### ISSUE THREAD

**Issue by wnsdn1207** [wurstmeister/kafka-docker#605]
Hi,

i'm setting the kafka clustering on docker swarm. i refered to numbers of issues and docker-compose.yml files. but, i still having a same issue. 

here is the my "docker-compose.yml" url :
URL : https://gist.github.com/wnsdn1207/3b9b649aefd6330da816aee29de9a91c

`
[2020-06-18 01:10:10,853] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka.common.InconsistentBrokerIdException: Configured broker.id 2 doesn't match stored broker.id 1 in meta.properties. If you moved your data, make sure your configured broker.id matches. If you intend to create a new broker, you should remove all data in your data directories (log.dirs).
at kafka.server.KafkaServer.getOrGenerateBrokerId(KafkaServer.scala:767)
at kafka.server.KafkaServer.startup(KafkaServer.scala:226)
at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:44)
at kafka.Kafka$.main(Kafka.scala:82)
at kafka.Kafka.main(Kafka.scala)
`

i wanna kafka clustering system on docker swarm. (zookeeper: 3, kafka: 3)

check my compose file and help me your opinion

**Comment by OneCricketeer** [comment]
Do you really need Swarm? This is a solved problem in the various kubernetes Helm Charts and operators for Kafka

**Comment by wnsdn1207** [comment]
@OneCricketeer 
you mean, in order to solve this issue, i would need to use the kubernetes ??

**Comment by OneCricketeer** [comment]
No, I'm asking if you really need to use Swarm?

**Comment by wnsdn1207** [comment]
I'm planning to make clustering using 3 zk - 3 kf.

Currently, i'm using 1 zk - 3 kf. 
In this case, if zookeeper server is dead, it's critical.

So i just wanna make clustering using 3 kf on 3 zk clustering system.

**Comment by OneCricketeer** [comment]
That's perfectly valid. You'll have just need 6 physical servers.

Doesn't answer the question though

**Comment by OneCricketeer** [comment]
Checkout https://strimzi.io/

**Comment by sscaling** [comment]
Given the error I'm assuming this came after a restart? It doesn't look like you have any placement constraints to force the kafka nodes to always run on the same host. Make sure you understand https://docs.docker.com/engine/swarm/services/#control-service-placement. 

Of course you could be using DFS / attached storage making physical location of containers less relevant - but without understanding the underlying topology it's a guessing game. When asking for help you should include as much information as possible and ideally the minimal reproducible example / steps.

**Comment by gerassimos** [comment]
I have the same issue and I am using 1 node swarm cluster.
