### ISSUE TITLE
docker-credential-gcloud not installed or not available 

### ISSUE THREAD

**Issue by echang0929** [wurstmeister/kafka-docker#621]
I got an issue:
```
➜ docker-compose up -d
Building kafka
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 1078, in up
  File "compose/cli/main.py", line 1074, in up
  File "compose/project.py", line 548, in up
  File "compose/service.py", line 367, in ensure_image_exists
  File "compose/service.py", line 1106, in build
  File "site-packages/docker/api/build.py", line 261, in build
  File "site-packages/docker/api/build.py", line 308, in _set_auth_headers
  File "site-packages/docker/auth.py", line 311, in get_all_credentials
  File "site-packages/docker/auth.py", line 262, in _resolve_authconfig_credstore
  File "site-packages/docker/auth.py", line 287, in _get_store_instance
  File "site-packages/docker/credentials/store.py", line 25, in __init__
docker.credentials.errors.InitializationError: docker-credential-gcloud not installed or not available in PATH
[25345] Failed to execute script docker-compose
``` 
Does this docker depend on google cloud env?

**Comment by echang0929** [comment]
It is just my local docker configure issue. 
Just remove all item related to gcloud in file ~/.docker/config.json
