### ISSUE TITLE
How can I interact with kafka cluster

### ISSUE THREAD

**Issue by xixiangzouyibian** [wurstmeister/kafka-docker#622]
Hi , As I successfully startup docker-compose, list running container:

- 6c00ba1e7181        kafka-docker-master_kafka   "start-kafka.sh"    0.0.0.0:32768->9092/tcp      kafka-docker-master_kafka_1
- 925cad87b9c7        wurstmeister/zookeeper    "/bin/sh -c '/usr/sb…"   22/tcp, 2888/tcp, 3888/tcp, 0.0.0.0:2181->2181/tcp   kafka-docker-master_zookeeper_1

Then I interact with my kafka cluster by "start-kafka-shell.sh", Now I want to run test case as http://wurstmeister.github.io/kafka-docker/ said, 
Executing command:  

- kafka-topics.sh --create --topic martin-topic --partitions 4 --zookeeper localhost:2181 --replication-factor 2

And got:

- Exception in thread "main" kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING

        at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:262)
        at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:119)
        at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1865)
        at kafka.admin.TopicCommand$ZookeeperTopicService$.apply(TopicCommand.scala:360)
        at kafka.admin.TopicCommand$.main(TopicCommand.scala:55)
        at kafka.admin.TopicCommand.main(TopicCommand.scala)

Is there something wrong for zookeeper input value, could you please kindly suggest ?
By the way, I running docker on windows 10 docker-desktop for newest version

**Comment by xixiangzouyibian** [comment]
Solved as I tried to use physical machine IP address...
