### ISSUE TITLE
InvalidReceiveException error 

### ISSUE THREAD

**Issue by LeamonLee** [wurstmeister/kafka-docker#634]
Hello,
I'm facing the following issue when I ran my docker-compose.
I have no idea which part goes wrong. Can anyone help me out? Thanks

**Docker compose file:**
version: "3"
services:
  zookeeper:
    image: zookeeper
    restart: always
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
    - 9092:9092
    - 9093:9093
    - 9094:9094
    environment:
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,HOST://0.0.0.0:9093,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,HOST://localhost:9093,OUTSIDE://172.22.75.200:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,HOST:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    container_name: kakfa-manager
    restart: always
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null

**Error:**
[2020-12-29 03:03:58,933] WARN [SocketServer brokerId=1001] Unexpected error from /172.29.24.1; closing connection (org.apache.kafka.common.network.Selector)                                                    
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)                                                                                               
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:104)                                                                                                                      
        at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:335)                                                                                                                           
        at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:296)                                                                                                                              
        at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:560)                                                                                                                               
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:496)                                                                                                                         
        at org.apache.kafka.common.network.Selector.poll(Selector.java:425)                                                                                                                                      
        at kafka.network.Processor.poll(SocketServer.scala:678)                                                                                                                                                  
        at kafka.network.Processor.run(SocketServer.scala:583)                                                                                                                                                   
        at java.lang.Thread.run(Thread.java:748)

**Comment by btilongnguyen** [comment]
Is there anything new on this issue? I'm facing the same error on an Apple M1 MacBook.
