### ISSUE TITLE
Specifying KAFKA_ADVERTISED_PORT Throws Exception

### ISSUE THREAD

**Issue by amarcionek** [wurstmeister/kafka-docker#64]
When specifying KAFKA_ADVERTISED_PORT, the Kafka containers won't start.  Trace:

`java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:493)
        at java.lang.Integer.parseInt(Integer.java:514)
        at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:229)
        at scala.collection.immutable.StringOps.toInt(StringOps.scala:31)
        at kafka.utils.VerifiableProperties.getIntInRange(VerifiableProperties.scala:75)
        at kafka.utils.VerifiableProperties.getIntInRange(VerifiableProperties.scala:48)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:75)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:31)
        at kafka.Kafka$.main(Kafka.scala:35)
        at kafka.Kafka.main(Kafka.scala)`

KafkaConfig.scala:75 is setting the broker ID.  So as a workaround, we specified KAFKA_BROKER_ID manually in the compose file and that worked.

I'm not sure if this is intentional or not? I see the start script sets the broker id, but it seems to do it off the hostname not the port? 
`if [[ -z "$KAFKA_BROKER_ID" ]]; then
    export KAFKA_BROKER_ID=$(docker inspect `hostname` | jq --raw-output '.[0] | .Name' | awk -F_ '{print $3}')
fi`

**Comment by ibizaman** [comment]
Do you still have the problem? I'm using the docker image pushed to docker hub and can set KAFKA_ADVERTISED_PORT without specifying a broker id.

**Comment by amarcionek** [comment]
The latest start-script changes the way the KAFKA_BROKER_ID is assigned.  If not specified in the environment, instead of using the hostname it now sets it to -1, thereby telling Kafka to auto-assign it.  So this issue should be closed.  I won't be able to test it for awhile, but I think the logic and your experience are enough to close the issue. Thanks!
