### ISSUE TITLE
Missing support for zstd compression in `2.13-2.7.0`

### ISSUE THREAD

**Issue by jszwedko** [wurstmeister/kafka-docker#669]
Hi all,

When upgrading to the latest tag, `2.13-2.7.0` we observed that the broker seems to no longer support zstd compression. In the broker logs I see:

```
[2021-06-07 18:46:40,838] ERROR [ReplicaManager broker=1] Error processing append operation on partition test-CvAFYOCTqd-20210607-0 (kafka.server.ReplicaManager)
org.apache.kafka.common.KafkaException: java.lang.UnsatisfiedLinkError: /tmp/libzstd-jni2390705912786063537.so: Error loading shared library libgcc_s.so.1: No such file or directory (needed by /tmp/libz
std-jni2390705912786063537.so)
no zstd-jni in java.library.path
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system.
        at org.apache.kafka.common.record.CompressionType$5.wrapForInput(CompressionType.java:133)
        at org.apache.kafka.common.record.DefaultRecordBatch.compressedIterator(DefaultRecordBatch.java:261)
        at org.apache.kafka.common.record.DefaultRecordBatch.skipKeyValueIterator(DefaultRecordBatch.java:340)
        at kafka.log.LogValidator$.$anonfun$validateMessagesAndAssignOffsetsCompressed$1(LogValidator.scala:403)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at kafka.log.LogValidator$.validateMessagesAndAssignOffsetsCompressed(LogValidator.scala:396)
        at kafka.log.LogValidator$.validateMessagesAndAssignOffsets(LogValidator.scala:106)
        at kafka.log.Log.$anonfun$append$2(Log.scala:1126)
        at kafka.log.Log.append(Log.scala:2387)
        at kafka.log.Log.appendAsLeader(Log.scala:1050)
        at kafka.cluster.Partition.$anonfun$appendRecordsToLeader$1(Partition.scala:1079)
        at kafka.cluster.Partition.appendRecordsToLeader(Partition.scala:1067)
        at kafka.server.ReplicaManager.$anonfun$appendToLocalLog$4(ReplicaManager.scala:953)
        at scala.collection.StrictOptimizedMapOps.map(StrictOptimizedMapOps.scala:28)
        at scala.collection.StrictOptimizedMapOps.map$(StrictOptimizedMapOps.scala:27)
        at scala.collection.mutable.HashMap.map(HashMap.scala:35)
        at kafka.server.ReplicaManager.appendToLocalLog(ReplicaManager.scala:941)
        at kafka.server.ReplicaManager.appendRecords(ReplicaManager.scala:621)
        at kafka.server.KafkaApis.handleProduceRequest(KafkaApis.scala:625)
        at kafka.server.KafkaApis.handle(KafkaApis.scala:137)
        at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:74)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libzstd-jni2390705912786063537.so: Error loading shared library libgcc_s.so.1: No such file or directory (needed by /tmp/libzstd-jni2390705912786063537.so
)
no zstd-jni in java.library.path
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system.
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
        at java.lang.Runtime.loadLibrary0(Runtime.java:872)
        at java.lang.System.loadLibrary(System.java:1124)
        at com.github.luben.zstd.util.Native.load(Native.java:105)
        at com.github.luben.zstd.util.Native.load(Native.java:54)
        at com.github.luben.zstd.ZstdInputStream.<clinit>(ZstdInputStream.java:21)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.apache.kafka.common.record.CompressionType.findConstructor(CompressionType.java:226)
        at org.apache.kafka.common.record.CompressionType.access$100(CompressionType.java:37)
        at org.apache.kafka.common.record.CompressionType$ZstdConstructors.<clinit>(CompressionType.java:218)
        at org.apache.kafka.common.record.CompressionType$5.wrapForInput(CompressionType.java:131)
        ... 21 more
```

It does work with the `2.13-2.6.0` tag though.

I didn't see anything relevant in https://kafka.apache.org/27/documentation.html#upgrade so I was unsure if this was due to a change in the docker image configuration or kafka itself. Apologies for the noise if it is the latter.

**Comment by filuta** [comment]
Hi all,
we have the same problem, zstd compression does not work with `2.13-2.7.0`. 
We've been using tag `2.13-2.7.0` for testing for several months and I'm quite sure this used to work. Then we redeployed the kafka cluster (on 2021-06-21) and it stopped working.
I've noticed there is a recent change of base image (https://github.com/wurstmeister/kafka-docker/commit/82a4f74ec7808393d7eb7063ed624242697d04c7) - can this be the cause of the issue?

An exception from broker's log:
```
[2021-06-21 12:35:22,446] ERROR [ReplicaManager broker=3] Error processing append operation on partition KafkaWriterAttrCompressionType_test-1 (kafka.server.ReplicaManager)
org.apache.kafka.common.KafkaException: java.lang.UnsatisfiedLinkError: /tmp/libzstd-jni4310126340891820225.so: Error loading shared library libgcc_s.so.1: No such file or directory (needed by /tmp/libzstd-jni4310126340891820225.so)
no zstd-jni in java.library.path
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system.
   at org.apache.kafka.common.record.CompressionType$5.wrapForInput(CompressionType.java:133)
   at org.apache.kafka.common.record.DefaultRecordBatch.compressedIterator(DefaultRecordBatch.java:261)
   at org.apache.kafka.common.record.DefaultRecordBatch.skipKeyValueIterator(DefaultRecordBatch.java:340)
   at kafka.log.LogValidator$.$anonfun$validateMessagesAndAssignOffsetsCompressed$1(LogValidator.scala:403)
   at java.lang.Iterable.forEach(Iterable.java:75)
   at kafka.log.LogValidator$.validateMessagesAndAssignOffsetsCompressed(LogValidator.scala:396)
   at kafka.log.LogValidator$.validateMessagesAndAssignOffsets(LogValidator.scala:106)
   at kafka.log.Log.$anonfun$append$2(Log.scala:1126)
   at kafka.log.Log.append(Log.scala:2387)
   at kafka.log.Log.appendAsLeader(Log.scala:1050)
   at kafka.cluster.Partition.$anonfun$appendRecordsToLeader$1(Partition.scala:1079)
   at kafka.cluster.Partition.appendRecordsToLeader(Partition.scala:1067)
   at kafka.server.ReplicaManager.$anonfun$appendToLocalLog$4(ReplicaManager.scala:953)
   at scala.collection.StrictOptimizedMapOps.map(StrictOptimizedMapOps.scala:28)
   at scala.collection.StrictOptimizedMapOps.map$(StrictOptimizedMapOps.scala:27)
   at scala.collection.mutable.HashMap.map(HashMap.scala:35)
   at kafka.server.ReplicaManager.appendToLocalLog(ReplicaManager.scala:941)
   at kafka.server.ReplicaManager.appendRecords(ReplicaManager.scala:621)
   at kafka.server.KafkaApis.handleProduceRequest(KafkaApis.scala:625)
   at kafka.server.KafkaApis.handle(KafkaApis.scala:137)
   at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:74)
   at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libzstd-jni4310126340891820225.so: Error loading shared library libgcc_s.so.1: No such file or directory (needed by /tmp/libzstd-jni4310126340891820225.so)
no zstd-jni in java.library.path
Unsupported OS/arch, cannot find /linux/amd64/libzstd-jni.so or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system.
   at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
   at java.lang.Runtime.loadLibrary0(Runtime.java:872)
   at java.lang.System.loadLibrary(System.java:1124)
   at com.github.luben.zstd.util.Native.load(Native.java:105)
   at com.github.luben.zstd.util.Native.load(Native.java:54)
   at com.github.luben.zstd.ZstdInputStream.<clinit>(ZstdInputStream.java:21)
   at java.lang.Class.forName0(Native Method)
   at java.lang.Class.forName(Class.java:264)
   at org.apache.kafka.common.record.CompressionType.findConstructor(CompressionType.java:226)
   at org.apache.kafka.common.record.CompressionType.access$100(CompressionType.java:37)
   at org.apache.kafka.common.record.CompressionType$ZstdConstructors.<clinit>(CompressionType.java:218)
   at org.apache.kafka.common.record.CompressionType$5.wrapForInput(CompressionType.java:131)
   ... 21 more
```
