### ISSUE TITLE
Can not connect to kafka after long time inactivation

### ISSUE THREAD

**Issue by h-gj** [wurstmeister/kafka-docker#676]
Kafak producer is currently unable to connect to kafka after long time inactivation.
I am using kafka-python (2.0.2).
Below is code of my kafka producer which is using Flask.
```Python
from flask import Flask, request
import json
from kafka import KafkaProducer


app = Flask(__name__)
app.debug = True

producer = KafkaProducer(bootstrap_servers=['172.17.0.1:49154'], value_serializer=lambda v: json.dumps(v).encode('utf-8'))


@app.route("/", methods=['GET', 'POST'])
def hello_world():
    topic = request.json.get('topic')
    print('\nTOPIC: %s\nPAYLOAD: %s: \n' % (topic, request.json))
    producer.send('topic', request.json)
    return ""
```
Error:
```shell
[pid: 10281|app: 0|req: 2/3] 42.193.134.62 () {40 vars in 507 bytes} [Mon Jul 19 15:55:10 2021] POST / => generated 0 bytes in 60007 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "kafka_producer.py", line 16, in hello_world
    producer.send('topic', request.json)
  File "/usr/local/lib/python3.6/dist-packages/kafka/producer/kafka.py", line 576, in send
    self._wait_on_metadata(topic, self.config['max_block_ms'] / 1000.0)
  File "/usr/local/lib/python3.6/dist-packages/kafka/producer/kafka.py", line 703, in _wait_on_metadata
    "Failed to update metadata after %.1f secs." % (max_wait,))
kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
```

Logs in kafka docker container:
![image](https://user-images.githubusercontent.com/43122596/126127299-a40b7554-94c9-4c0a-82c4-06aa5ebaef98.png)

**Comment by h-gj** [comment]
I started the containers using ```docker compose up -d```. Here are my docker containers.
![image](https://user-images.githubusercontent.com/43122596/126127925-3e3bba44-8fa6-47b3-a5da-e00e03dd2ecb.png)
