### ISSUE TITLE
Getting TimeoutException: Topic not present in metadata after 60000 ms

### ISSUE THREAD

**Issue by Sourabh25** [wurstmeister/kafka-docker#695]
Hi,

I am trying to use https://hub.docker.com/r/wurstmeister/kafka image to build a kafka depliyment using kubernetes.

Please find below my configuration files

kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker0
  labels:
    name: kafka
    applicationid: ********
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
        applicationid: ********
    spec:
      containers:
        - name: kafka
          image: "kafka:latest"
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka-service
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-service:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo1:2181

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka
    applicationid: ********
spec:
  ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
  selector:
    app: kafka
    id: "0"

---
apiVersion: v1
kind: Service
metadata:
  name: zoo1
  labels:
    app: zookeeper-1
    applicationid: ********
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
  selector:
    app: zookeeper-1
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper-deploy
  labels:
    app: zookeeper-1
    applicationid: ********
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zookeeper-1
  template:
    metadata:
      labels:
        app: zookeeper-1
        applicationid: ********
    spec:
      containers:
        - name: zoo1
          image: "zookeeper:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_ID
              value: "1"
            - name: ZOOKEEPER_SERVER_1
              value: zoo1
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"

When I am trying to connect to this kafka server with my application, I am getting the below error:
org.springframework.kafka.KafkaException: Send failed; nested exception is org.apache.kafka.common.errors.TimeoutException: Topic <topicName> not present in metadata after 60000 ms.
	at org.springframework.kafka.core.KafkaTemplate.doSend(KafkaTemplate.java:574)
	at org.springframework.kafka.core.KafkaTemplate.send(KafkaTemplate.java:369)

Kindly let me know if I am missing anything here

**Comment by OneCricketeer** [comment]
Without seeing your Spring application config, it is unclear what address it is connected to. 

You might want to try Strimzi instead, and make sure to read it's section on allowing external service listeners - https://strimzi.io/
