### ISSUE TITLE
Kafka failing during startup doesn't force Docker container to exit

### ISSUE THREAD

**Issue by olvesh** [wurstmeister/kafka-docker#72]
I do some rapid restarts during an Ansible install and the Kafka server complains that:
```
[2016-02-04 15:35:04,556] INFO [Kafka Server 102011155], shut down completed (kafka.server.KafkaServer)
[2016-02-04 15:35:04,557] FATAL Fatal error during KafkaServerStartable startup. Prepare to shutdown (kafka.server.KafkaServerStartable)
java.lang.RuntimeException: A broker is already registered on the path /brokers/ids/102011155. This probably indicates that you either have configured a brokerid that is already in use, or else you have shutdown this broker and restarted it faster than the zookeeper timeout so it appears to be re-registering.
	at kafka.utils.ZkUtils.registerBrokerInZk(ZkUtils.scala:295)
	at kafka.utils.ZkUtils.registerBrokerInZk(ZkUtils.scala:281)
	at kafka.server.KafkaHealthcheck.register(KafkaHealthcheck.scala:64)
	at kafka.server.KafkaHealthcheck.startup(KafkaHealthcheck.scala:45)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:231)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:37)
	at kafka.Kafka$.main(Kafka.scala:67)
	at kafka.Kafka.main(Kafka.scala)
[2016-02-04 15:35:04,558] INFO [Kafka Server 102011155], shutting down (kafka.server.KafkaServer)
```

But the docker image is still running:
```
ip-10-20-11-155:/# ps fax
PID   USER     TIME   COMMAND
    1 root       0:00 {start-kafka.sh} /bin/bash /usr/bin/start-kafka.sh
  179 root       0:00 sh -l
  233 root       0:00 sleep 1
  236 root       0:00 ps fax
```

I have fixed my Ansible scripts so that there is a pause letting the Kafka servers ZK connection time out, but it is worrying that the container keeps on running while Kafka is shut down.

Is it possible to detect this somehow and retry even though the START_TIMEOUT of 10 minutes  is not passed?

**Comment by wurstmeister** [comment]
Hi,

thanks for raising this issues. i've separated the topic creation from the startup process which should solve the problem (https://github.com/wurstmeister/kafka-docker/commit/e03b1d6af16a3062ddcae2d5b9e190328c8eae45). Please let me know if this solves the problem for you. 


```
kafka_1     | [2016-02-04 23:08:16,434] INFO [Kafka Server 1003], shut down completed (kafka.server.KafkaServer)
kafka_1     | [2016-02-04 23:08:16,435] FATAL Fatal error during KafkaServerStartable startup. Prepare to shutdown (kafka.server.KafkaServerStartable)
kafka_1     | java.lang.RuntimeException: A broker is already registered on the path /brokers/ids/1003. This probably indicates that you either have configured a brokerid that is already in use, or else you have shutdown this broker and restarted it faster than the zookeeper timeout so it appears to be re-registering.
kafka_1     | 	at kafka.utils.ZkUtils.registerBrokerInZk(ZkUtils.scala:295)
kafka_1     | 	at kafka.utils.ZkUtils.registerBrokerInZk(ZkUtils.scala:281)
kafka_1     | 	at kafka.server.KafkaHealthcheck.register(KafkaHealthcheck.scala:64)
kafka_1     | 	at kafka.server.KafkaHealthcheck.startup(KafkaHealthcheck.scala:45)
kafka_1     | 	at kafka.server.KafkaServer.startup(KafkaServer.scala:231)
kafka_1     | 	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:37)
kafka_1     | 	at kafka.Kafka$.main(Kafka.scala:67)
kafka_1     | 	at kafka.Kafka.main(Kafka.scala)
kafka_1     | [2016-02-04 23:08:16,436] INFO [Kafka Server 1003], shutting down (kafka.server.KafkaServer)
kafkadocker_kafka_1 exited with code 1
```

**Comment by olvesh** [comment]
Thx for the fix - that looked much better indeed! 
But I am not too fond of running `latest` on public images -  are you considering cutting a release on these changes?

**Comment by wurstmeister** [comment]
it's tagged now (0.9.0.0-1)

**Comment by olvesh** [comment]
thx
