### ISSUE TITLE
[KafkaServer id=2] Fatal error during KafkaServer shutdown. (kafka.server.KafkaServer)

### ISSUE THREAD

**Issue by hubcomsix** [wurstmeister/kafka-docker#749]
# CurrentBehavior
[2024-07-09 15:22:53,622] ERROR [KafkaServer id=2] Fatal error during KafkaServer shutdown. (kafka.server.KafkaServer)
java.lang.IllegalStateException: Kafka server is still starting up, cannot shut down!
        at kafka.server.KafkaServer.shutdown(KafkaServer.scala:670)
        at kafka.server.KafkaServerStartable.shutdown(KafkaServerStartable.scala:54)
        at kafka.Kafka$.$anonfun$main$3(Kafka.scala:80)
        at kafka.utils.Exit$.$anonfun$addShutdownHook$1(Exit.scala:38)
        at java.lang.Thread.run(Thread.java:750)
[2024-07-09 15:22:53,629] ERROR Halting Kafka. (kafka.server.KafkaServerStartable)

**Comment by OneCricketeer** [comment]
Please provide more details about your setup and what commands you're running. What versions, what host OS, etc.

Note - there's an officially maintained Apache Kafka docker image now rather than this one
