### ISSUE TITLE
Kafka producers experience frequent connection timeouts and message sending failures under high loads

### ISSUE THREAD

**Issue by CCTV-six** [wurstmeister/kafka-docker#754]
### CurrentBehavior
Kafka producers have experienced frequent connection timeouts and message sending failures under high loads. Producers occasionally throw org.apache.kafka.common.errors when calling the send() method TimeoutException
And I saw the following error message in the log:
[ERROR] KafkaProducer: Exception while sending a message: 
org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node to become available.
    at org.apache.kafka.clients.producer.internals.Sender.sendProducerData(Sender.java:435)
    at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:804)
    at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:748)
### ExpectedBehavior
Producers should be able to maintain stable connections with Kafka clusters, and messages should be successfully sent even under high loads and network fluctuations.

**Comment by OneCricketeer** [comment]
This has nothing to do with the docker image
