### ISSUE TITLE
ERROR Processor got uncaught exception. (kafka.network.Processor) java.nio.BufferUnderflowException

### ISSUE THREAD

**Issue by willfarrell** [wurstmeister/kafka-docker#90]
Is this an issue with kafka directly? I'm not doing anything special. Just testing kafka on my localhost (Mac).

### Process:
update docker-compose-single-broker.yml to use `KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100`

```bash
docker-compose -f docker-compose-single-broker.yml up -d`
npm install kafka
node test.js # See below for code.
```

node Results:
```bash
Consumer Connected
Producer Connected
```

docker Result:
```bash
ERROR Processor got uncaught exception. (kafka.network.Processor)
kafka_1      | java.nio.BufferUnderflowException
kafka_1      | 	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
kafka_1      | 	at java.nio.ByteBuffer.get(ByteBuffer.java:715)
kafka_1      | 	at kafka.api.ApiUtils$.readShortString(ApiUtils.scala:40)
kafka_1      | 	at kafka.api.FetchRequest$.readFrom(FetchRequest.scala:42)
kafka_1      | 	at kafka.api.RequestKeys$$anonfun$2.apply(RequestKeys.scala:49)
kafka_1      | 	at kafka.api.RequestKeys$$anonfun$2.apply(RequestKeys.scala:49)
kafka_1      | 	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:66)
kafka_1      | 	at kafka.network.Processor$$anonfun$run$11.apply(SocketServer.scala:426)
kafka_1      | 	at kafka.network.Processor$$anonfun$run$11.apply(SocketServer.scala:421)
kafka_1      | 	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
kafka_1      | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
kafka_1      | 	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
kafka_1      | 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
kafka_1      | 	at kafka.network.Processor.run(SocketServer.scala:421)
kafka_1      | 	at java.lang.Thread.run(Thread.java:745)
```

test.js
```javascript
var kafka = require('kafka');

var comm = {
	host:         '192.168.99.100',
	port:          9092
};

new kafka.Consumer(comm).connect().on('connect', function() {
	console.log("Consumer Connected");
}).subscribeTopic('topic').on('message', function(topic, message) {
	console.log("Consumed message:", message)
});

var producer = new kafka.Producer({
	host:         '192.168.99.100',
	port:         9092,
	topic:        'topic',
	partition:    1
}).connect().on('connect', function() {
	console.log('Producer Connected');
	producer.send("hey!");
	producer.close()
});
```

**Comment by willfarrell** [comment]
Turns out it was the node module.

**Comment by sybrandy** [comment]
@willfarrell Do you know what was wrong with the node module that cause this exception?  I'm seeing the same exception in my logs, but we're not connecting via node and we have a couple different things connecting to Kafka, so some additional details would be great if you still have them.

**Comment by willfarrell** [comment]
I honestly don't remember. It's possible I never got it working. Kafka was pushed to the backlog and is still there.
